// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OnlinAuctionWebsite.Data;

namespace OnlinAuctionWebsite.Migrations
{
    [DbContext(typeof(AuctionOnlineDbContext))]
    partial class AuctionOnlineDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.11")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("OnlinAuctionWebsite.Models.Bid_Coin_Pack", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Bid_Coins_Value")
                        .HasColumnType("int");

                    b.Property<int>("Bonus_Coin")
                        .HasColumnType("int");

                    b.Property<int>("Cost")
                        .HasColumnType("int");

                    b.Property<string>("Pack_Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Bid_Coin_Packs");
                });

            modelBuilder.Entity("OnlinAuctionWebsite.Models.Bid_Coin_Trans_Log", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("Bid_Coin_Pack_IDID")
                        .HasColumnType("int");

                    b.Property<int?>("Bid_Order_Log_IDID")
                        .HasColumnType("int");

                    b.Property<int?>("Bidder_IDID")
                        .HasColumnType("int");

                    b.Property<int>("Coin_Count")
                        .HasColumnType("int");

                    b.Property<DateTime>("Transaction_Date")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.HasIndex("Bid_Coin_Pack_IDID");

                    b.HasIndex("Bid_Order_Log_IDID");

                    b.HasIndex("Bidder_IDID");

                    b.ToTable("Bid_Coin_Trans_Logs");
                });

            modelBuilder.Entity("OnlinAuctionWebsite.Models.Bid_Order", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Base_Price")
                        .HasColumnType("int");

                    b.Property<int>("Bid_Chair_Cost")
                        .HasColumnType("int");

                    b.Property<DateTime>("Bid_End_Time")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Bid_Start_Time")
                        .HasColumnType("datetime2");

                    b.Property<int?>("BidderID")
                        .HasColumnType("int");

                    b.Property<int>("Cool_Down_Time_Per_Bid")
                        .HasColumnType("int");

                    b.Property<int>("Increment_Price_Per_Bid")
                        .HasColumnType("int");

                    b.Property<int>("Product_ID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("BidderID");

                    b.ToTable("Bid_Orders");
                });

            modelBuilder.Entity("OnlinAuctionWebsite.Models.Bid_Order_Log", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("Bidder_Bid_Regist_IDID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("Bidder_Bid_Regist_IDID");

                    b.ToTable("Bid_Order_Logs");
                });

            modelBuilder.Entity("OnlinAuctionWebsite.Models.Bidder", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Current_bid_coins")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date_of_birth")
                        .HasColumnType("datetime2");

                    b.Property<string>("First_Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Identity_Card_Number")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("JoinDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Last_Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Locked_bid_coins")
                        .HasColumnType("int");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone_number")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("User_Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Bidders");
                });

            modelBuilder.Entity("OnlinAuctionWebsite.Models.Bidder_Bid_Regist", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("Bidder_IDID")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("MyProperty")
                        .HasColumnType("int");

                    b.Property<DateTime>("Regist_Date")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.HasIndex("Bidder_IDID");

                    b.ToTable("Bidder_Bid_Regists");
                });

            modelBuilder.Entity("OnlinAuctionWebsite.Models.Product", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Actual_cost_in_curency")
                        .HasColumnType("int");

                    b.Property<string>("Product_Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Product_Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Sub_CategoryID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("Sub_CategoryID");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("OnlinAuctionWebsite.Models.Product_Category", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Cat_Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Category")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Product_Categories");
                });

            modelBuilder.Entity("OnlinAuctionWebsite.Models.Product_Image", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Product_IDID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("Product_IDID");

                    b.ToTable("Product_Images");
                });

            modelBuilder.Entity("OnlinAuctionWebsite.Models.Sub_Category", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CategoryID")
                        .HasColumnType("int");

                    b.Property<string>("Sub_Category_Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("CategoryID");

                    b.ToTable("Sub_category");
                });

            modelBuilder.Entity("OnlinAuctionWebsite.Models.Bid_Coin_Trans_Log", b =>
                {
                    b.HasOne("OnlinAuctionWebsite.Models.Bid_Coin_Pack", "Bid_Coin_Pack_ID")
                        .WithMany()
                        .HasForeignKey("Bid_Coin_Pack_IDID");

                    b.HasOne("OnlinAuctionWebsite.Models.Bid_Order_Log", "Bid_Order_Log_ID")
                        .WithMany()
                        .HasForeignKey("Bid_Order_Log_IDID");

                    b.HasOne("OnlinAuctionWebsite.Models.Bidder", "Bidder_ID")
                        .WithMany()
                        .HasForeignKey("Bidder_IDID");

                    b.Navigation("Bid_Coin_Pack_ID");

                    b.Navigation("Bid_Order_Log_ID");

                    b.Navigation("Bidder_ID");
                });

            modelBuilder.Entity("OnlinAuctionWebsite.Models.Bid_Order", b =>
                {
                    b.HasOne("OnlinAuctionWebsite.Models.Bidder", "Bidder")
                        .WithMany("Bid_Orders")
                        .HasForeignKey("BidderID");

                    b.Navigation("Bidder");
                });

            modelBuilder.Entity("OnlinAuctionWebsite.Models.Bid_Order_Log", b =>
                {
                    b.HasOne("OnlinAuctionWebsite.Models.Bidder_Bid_Regist", "Bidder_Bid_Regist_ID")
                        .WithMany()
                        .HasForeignKey("Bidder_Bid_Regist_IDID");

                    b.Navigation("Bidder_Bid_Regist_ID");
                });

            modelBuilder.Entity("OnlinAuctionWebsite.Models.Bidder_Bid_Regist", b =>
                {
                    b.HasOne("OnlinAuctionWebsite.Models.Bidder", "Bidder_ID")
                        .WithMany("Bidder_Bid_Regists")
                        .HasForeignKey("Bidder_IDID");

                    b.Navigation("Bidder_ID");
                });

            modelBuilder.Entity("OnlinAuctionWebsite.Models.Product", b =>
                {
                    b.HasOne("OnlinAuctionWebsite.Models.Sub_Category", "Sub_Category")
                        .WithMany("Products")
                        .HasForeignKey("Sub_CategoryID");

                    b.Navigation("Sub_Category");
                });

            modelBuilder.Entity("OnlinAuctionWebsite.Models.Product_Image", b =>
                {
                    b.HasOne("OnlinAuctionWebsite.Models.Product", "Product_ID")
                        .WithMany("Prodcut_Images")
                        .HasForeignKey("Product_IDID");

                    b.Navigation("Product_ID");
                });

            modelBuilder.Entity("OnlinAuctionWebsite.Models.Sub_Category", b =>
                {
                    b.HasOne("OnlinAuctionWebsite.Models.Product_Category", "Category")
                        .WithMany("Sub_Categories")
                        .HasForeignKey("CategoryID");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("OnlinAuctionWebsite.Models.Bidder", b =>
                {
                    b.Navigation("Bid_Orders");

                    b.Navigation("Bidder_Bid_Regists");
                });

            modelBuilder.Entity("OnlinAuctionWebsite.Models.Product", b =>
                {
                    b.Navigation("Prodcut_Images");
                });

            modelBuilder.Entity("OnlinAuctionWebsite.Models.Product_Category", b =>
                {
                    b.Navigation("Sub_Categories");
                });

            modelBuilder.Entity("OnlinAuctionWebsite.Models.Sub_Category", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
