USE AuctionOnline
GO

INSERT INTO Product_Categories VALUES 
('Art','Art.jpg'),
('Vehicle','Vehicle.jpg'),
('Antique','Antique.jpg'),
('Fashion','Fashion.jpg'),
('Electronics','Electronic.jpg'),
('Collection','Collection.jpg')
('Sports','Sports.jpg'),
('Toys & Game','Toys&Game.jpg'),
('Beauty & Comestic','Beauty&Comestics.jpg'),

SELECT * FROM Product_Categories
GO

INSERT INTO Sub_category VALUES
--Art category
('Oil Painting',1),
('Classic Painting',1),
('Art Photo',1),
--Vehicle
('Car',2),
('Boat',2),
('Plane',2),
--Antique
('Furniture Antiques',3),
('Ancient Pottery',3),
('Ancient Clock',3),
('Ancient Weapons',3),
('Ancient Books',3),
--Fashion
('Bracelet',4),
('Necklace',4),
('Fashion Shoes',4),
('Dress',4),
('Jacket',4),
('Jeans',4),
('Watch',4),
--Electronics
('Phone',5),
('Computer',5),
('Electronice device',5),
--Collection--
('Wine',6),
('Stamp',6),
('Coin',6),
('Card',6),
--Sports--
(' 
--Toys & Game--
--Beauty&Comestic--
SELECT * FROM Sub_category
GO
DELETE FROM Sub_category
INSERT INTO Products VALUES 
--ART--
	 --Oil Painting--
('Mona Lisa','Mona Lisa is one of the most famous oil paintings in the world. A 16th-century portrait painted in oil on a poplar panel in Florence by Leonardo da Vinci during the Italian Renaissance. The work is owned by the French Government and is currently on display at the Louvre in Paris, France as Portrait of Lisa Gherardini, wife of Francesco del Giocondo',15000,1),
('The Starry Night','Painted in June 1889, the painting depicts the scene outside the window of his hospital room in Saint-Rémy-de-Provence, southern France at night, although he painted the picture during the day through his mind. mind. The Starry Night is in the collection of the Museum of Modern Art in New York City, part of the Relics of Lillie P. Bliss, from 1941. The painting is one of van Gogh most famous works. , marking a decisive turning point towards greater creative freedom in his art.',6000 ,1),
('Girl with a Pearl Earring','The oil painting, born around 1665, has been especially noticed by art lovers since becoming the subject of the best-selling historical novel of the same name, published by writer Tracy Chevalier in 1999.Until now, art experts have not been able to decipher the origin of this oil painting, because there is not much information about the artist as well as the model in the picture. The painting is currently on display at the Mauritshuis museum in Den Haag, Netherlands.',35000 ,1),
('The Cafe Terrace on the Place de Forum','This is the first oil painting Van Gogh painted the starry sky as the background. One year after painting Cafe Terrace, Van Gogh continued painting Starry Night. In a letter to his brother Theo, Van Gogh reminded of the Cafe Terrace that he painted "the scene of the cafe on the sidewalk of the Forum Hotel, where we used to go" and "painted at night".', 20000,1),
('The Birth of Venus','Botticellis oil painting The Birth of Venus is the first full-length, non-religious nude image since antiquity. The painting was painted for Lorenzo de Medici. Venus appeared on the seashore in a giant seashell next to the wind god Zephyrus and Aura as a sign of the arrival of spring in this land.',12000 ,1),
('Les Demoiselles d’Avignon','Les Demoiselles d’Avignon became an iconic oil painting of the 20th century, breaking with tradition commonly found in Western painting, incorporating the African masks Picasso saw at the ethnomuseum. study in Paris. The women depicted in the painting are actually prostitutes in the brothel in Barcelona, the artist’s hometown.',25000,1),
('The Kiss','The painting The Kiss marks Gustav Klimt’s heyday from 1899-1919 when he often used gold leaf - a technique inspired by a 1903 trip to the Basilica di San Vitale in Ravenna, Italy, where he saw the famous Byzantine mosaics of the church.',20000,1),
	--Classic Painting--
('American Gothic','American Gothic is a painting by Grant Wood from the collection of the Art Institute of Chicago.The painting shows a farmer standing next to his aunt.Real-life samples from the author. It is one of the most familiar images in American art,and is parodyed by many.', 15000,1),
('A night full of stars','Starry Night is a painting by artist post-impressionist who Netherlands Vincent Van Gogh. Painted in June 1889, the painting depicts the scene outside the window of his hospital room in Saint-Rémy-de-Provence , southern France at night, although he painted the picture during the day through his mind.',10000,1),
('Whistler’s Mother', 'James Abbott McNeill Whistler painted the work in his London studio in 1871, and in it, the formality of portraiture becomes an essay in form. Whistler’s mother Anna is pictured as one of several elements locked into an arrangement of right angles.', 9000,1),
('The Kiss','The Kiss, Gustav Klimt’s fin-de-siècle portrayal of intimacy, is a mix of Symbolism and Vienna Jugendstil, the Austrian variant of Art Nouveau. Klimt depicts his subjects as mythical figures made modern by luxuriant surfaces of up-to-the moment graphic motifs.The Kiss, Gustav Klimt’s fin-de-siècle portrayal of intimacy, is a mix of Symbolism and Vienna Jugendstil, the Austrian variant of Art Nouveau. Klimt depicts his subjects as mythical figures made modern by luxuriant surfaces of up-to-the moment graphic motifs',7000,1),
('The Last Supper','The Last Supper is a famous fresco by Leonardo da Vinci . The work was composed between 1495 and 1498. The fresco is located in the banquet hall of the Monastery of Santa Maria in Milan .', 9000,1),
('Las Meninas','Las Meninas ( Spanish maid of honor or simply The ladies ) is a picture painted in 1656 by Diego Velázquez , painter top heyday Spain , located in the museum Museo del Prado in Madrid. Thanks to these unique features, "Las Meninas" has become one of the most widely analyzed works in Western painting .',13000,1),
	--Art Photo--
('Wild Horses','Horse Photography - Mountains Wanderlust Travel photography by Ingrid Beddoes Art Print Horse Photography - Mountains Wanderlust Travel photography by Ingrid Beddoes Art PrintHorse Photography - Mountains Wanderlust Travel photography by Ingrid Beddoes Art PrintHorse Photography', 10000,1),
('These Boots - Glitter Pink Art Print','Beautiful print. Loved the colors and details. Not s Glossy print but matte and perfect. Only issue I found was being able to find a frame for the print size. I ended up having my boyfriend make a custom frame for me because he is a carpenter.', 15000,1),
('Scottish Highland cattle on a farm','Close up portrait of Scottish Highland cattle on a farm. This photographic print leverages sophisticated digital technology to capture a level of detail that is absolutely stunning. The colors are vivid and pure. The high-quality archival paper, a favorite choice among professional photographers, has a refined luster quality.',18000,1),
('Tree in Field of Flowers','Tree in Field of Flowers by Mia Friedrich is a tranquil art painting print that uses pastel colors to capture a blooming tree in the midst of a field of white flowers. Tree in Field of Flowers by Mia Friedrich is a tranquil art painting print that uses pastel colors to capture a blooming tree in the midst of a field of white flowers.',20000,1),
('Elmer','Keep your furry and feathery friends close, whether they are a galloping stallion or a dog taking a selfie. Our gallery is here to turn empty walls into a cute and quirky display of animal art. Keep your furry and feathery friends close, whether they are a galloping stallion or a dog taking a selfie. Our gallery is here to turn empty walls into a cute and quirky display of animal art.',15000,1),

--VEHICLE--
	--Ferrari--
('Ferrari SF90 Stradale','The SF90 Stradale is a plug-in hybrid electric vehicle. With a maximum capacity of 986 horsepower, a maximum speed of 340km / h and the ability to accelerate from 0-100km / h in 2.5s. This is the most powerful production Ferrari car to date. With a completely new exterior design, the interior is full of technology.Hypercar SF90 Stradale launched in May 2019 deserves to be a masterpiece but has a fairly cheap price.', 500000,5),
('Ferrari F12 Berlinetta','This super car with a handsome and handsome appearance contains tremendous power inside it. Equipped with a 6.3L V12 engine with a maximum capacity of 730Hp/8250rpm, maximum torque of 690Nm/6000rpm; 7-speed dual-clutch transmission; The car accelerates to 100km/h in 3.1s.', 200000,5),
('Ferrari 812 Superfast','812 Superfast will debut at the upcoming Geneva show. With a worthy replacement for the elder F12, the Ferrari 812 Superfast uses a slightly larger engine, 6.5L V12 with a capacity of 789Hp, a terrible torque of 718Nm. The car accelerates to 100km / h in 2.9s, faster than even LaFerrari.Top speed 339km/h. Due to late birth, 812 Superfast is also equipped with many new technologies. At this point, the official price of this accelerated champion is available.', 340000, 5),
('Ferrari 488GTB','Perhaps Ferrari 488GTB is the Ferrari model with the most volume to Vietnam, about over 10 cars by the end of 2016, simply the price of Ferrari 488GTB is considered quite reasonable, about 17-20 billion in Vietnam.Perhaps Ferrari 488GTB is the Ferrari model with the most volume to Vietnam, about over 10 cars by the end of 2016, simply the price of Ferrari 488GTB is considered quite reasonable, about 17-20 billion in Vietnam', 260000,5),
	--Hyundai--
('Hyundai Palisade','The Hyundai Palisade is a full-size SUV manufactured by Hyundai Motor (Korea). The car was first unveiled at the Los Angeles Auto Show in November 2018. Palisade is the flagship SUV of the Hyundai brand, the "elder" of Hyundai Santafe.In May 2019, the first Hyundai Palisade appeared in Vietnam in the form of original imports from Korea.',80000,2),
('Hyundai Accent 2021','Hyundai Accent 2021 facelift launched in November 2020.The Hyundai Accent is a small car (segment B-subcompact car) of the South Korean automaker Hyundai. Hyundais B-class sedan is still assembled domestically and has a very competitive price. In 2020, Accent has sold 20,776 cars, ranking 2nd in the top 15 best-selling cars in Vietnam (only behind rival Toyota Vios - 30,251 cars)',30000,5),
('Hyundai SantaFe','Hyundai SantaFe was first introduced in Vietnam in 2007, after more than 10 years and two generations, the Korean SUV model is trusted by customers thanks to its advantages in design as well as many amenities and handling capabilities. outstanding performance.Currently, the price of Hyundai SantaFe 2021 is  sold in October 2021 with 6 versions.',45000,2),
('Hyundai Kona 2021','Since its launch in the Vietnamese market, Hyundai Kona quickly beat Ecosport to become the best-selling urban small SUV. However, now Kona has had a harder time with the arrival of rookies Kia Seltos and Toyota Corolla Cross. The price of Hyundai Kona car  with 3 versions including standard AT, special AT and Turbo', 30000,2),
('Hyundai Grand i10 2021','Hyundai Grand i10  has continuously been one of the best-selling models of the number one Korean car brand in Vietnam for many years. The A-class car segment is increasingly competitive with a series of notable names such as Kia Morning, Toyota Wigo, VinFast Fadil, Honda Brio, ..Hyundai i10 car price is at 360-455 million VND for 6 different versions of both sedan and hatchback',20000,5),
('Hyundai Elantra 2021','The upgraded version of Hyundai Elantra  was officially introduced in Vietnam in mid-May 2019 with many notable upgrades both inside and out. The new Elantra version  has an appearance designed in the new language "Sensual Sportiness" to bring a strong and sporty feeling.Hyundai Elantra is one of the notable models in the C- segment car segment in Vietnam and competes directly with rivals Mazda 3, Kia Cerato, Toyota Corola Altis...',25000,5),
	--Toyota--
('WIGO 5MT','Get the 5-year/150,000 km warranty right away. The program is valid from June 7 to December 31, 2021. Possessing a sporty appearance with a youthful design language and a wide choice of colors, it deserves to be your first car. Possessing a sporty appearance with a youthful design language and a wide choice of colors, it deserves to be your first car.', 15000,5),
('CAMRY 2.0G','INTELLIGENT DESIGN LANGUAGE RICH. The 2019 Camry version brings a new, extremely eye-catching appearance with a seamlessness in every design detail, which is the focal point to attract eyes when surfing. Spacious, comfortable interior is improved with modern technology, creating a classy and peaceful space. Number of seats: 5 seats. Style: Sedan. 6-speed automatic transmission', 50000,5),
('LAND CRUISER PRADO VX', 'Inheriting the superficial, strong, and solid appearance of the world-famous off-road vehicle; With the design philosophy of "Modern - Smart", Land Cruiser Prado becomes the pride and contributes to enhancing the owner position on all terrains. Spacious space with high-class furniture and modern amenities, combining advanced technology to bring relaxation and great experience, honoring the owner style.', 40000,5),
('VIOS 1.5E MT', 'EMOTIONAL DESIGN. The new VIOS with its emotional design and 5-star safety technology will be an endless source of inspiration for you to explore every road. Experience the sophisticated and luxurious interior space with modern design language. The center console is accented with seamless silver-plated lines in the form of a waterfall flowing from the top. Number of seats: 5 seats. Style: Sedan. Fuel: Gasoline. Origin: Domestic car', 15000,5),
('COROLLA CROSS 1.8V', 'Impressive, dynamic appearance. The design direction of the Corolla Cross is aimed at mature and urban trends, different from current Toyota models. Impressive, dynamic appearance. The design direction of the Corolla Cross is aimed at mature and urban trends, different from current Toyota models. Impressive, dynamic appearance', 10000, 5),
	--Mercedes BenZ--
('Mercedes-AMG', 'Sporty style in luxury sedan design. Welcome to the Mercedes-AMG racetrack. I, the AMG A-Class Sedan, will pave the way to the world of speed and performance. Get in the car, fasten your seat belt, and get ready to experience the ENCOURAGE OF EVERY SECTION! An elegant style in dynamic appearance. Get sporty with the signature grille and AMG spirit-marked equipment. he new generation MBUX (Mercedes-Benz User Experience) infotainment system connects driver and vehicle in a fun way', 70000, 5),
('Mercedes E-Class', 'A more dynamic character all round. Ready to master even the greatest challenge with ease. Discover the outstanding properties of the new E-Class Sedan. As dynamic, elegant and luxurious as never before. The expressive design ensures an agile overall impression. The new E-Class Sedan scores points on several counts: with fine materials and intelligent innovations.', 50000,5),
('Mercedes Maybach S480', 'Mercedes Maybach S480 2021 is a completely new model and has the lowest price of the Maybach S-Class line, so the car has less equipment than other variants but the car design is not much different. The length of the car remains the same, the DxRxC parameters are 5,468x1,920x1,508 mm, and the wheelbase is 3,395 mm.At the front of the car, the Mercedes Maybach S480 has a large grille with chrome plated vertical spokes with the words Maybach on the top of the grille.', 20000,5),
('Mercedes E200 2021', 'The exterior of the new E200 Exclusive has a shift to a more elegant and luxurious style. The car is upgraded and equipped with 7 new points compared to the old E200. That shows that Mercedes has shaped the customer of the E200 as working or middle-aged people. The exterior of the new E200 Exclusive has a shift to a more elegant and luxurious style. The car is upgraded and equipped with 7 new points compared to the old E200.', 17000,5),

--ANTIQUE--
	--Furniture Antiques--
('Antique 1800s rocking chair','An item that has been used previously. The item may have some signs of cosmetic wear, but is fully operational and functions as intended. This item may be a floor model or store return that has been used. See the seller’s listing for full details and description of any imperfections', 200, 3),
('Vintage Wooden Vanity Dresser Table Mirror Swivel Frame Pedestal Victorian','Good vintage pre-owned condition; scratches in wood and flaws in glass. An item that has been used previously. The item may have some signs of cosmetic wear, but is fully operational and functions as intended. An item that has been used previously. The item may have some signs of cosmetic wear, but is fully operational and functions as intended', 1000,3),
('George Nelson Chess Piece Clock', 'Vintage Condition. Style: Mid-Century Modern. Charming middle bed, in the Empire taste, with structure entirely conceived in mahogany veneer.It is built around four detached columns, each surmounted at their ends by a solid mahogany ball. Rich and refined bronzes trimmings, finely chiselled, embellish them in their high and intermediate. Charming middle bed, in the Empire taste, with structure entirely conceived in mahogany veneer.', 6800,3),
('19th Century Empire Style Mahogany Bed','Vintage Design.Charming middle bed, in the Empire taste, with structure entirely conceived in mahogany veneer. It is built around four detached columns, each surmounted at their ends by a solid mahogany ball. Rich and refined bronzes trimmings, finely chiselled, embellish them in their high and intermediate',3600,3),
('Antique Estonian Dining Chairs from Luterma, 1910s','Set of 6 former pub chairs / bistro chairs from the Art Nouveau period around 1910. Particularly beautiful are the embossed seats, which together with their elegant swing make the chairs a real eye-catcher.Light wear consistent with age and use, Patina consistent with age and use, Partially restored, Surface has been polished, Surface has been refinished, Restored', 4000,3),
('Antique Writing Desk, 1700s', 'Louis XVI writing desk in inlaid walnut wood with front drawer. Good — This vintage item remains fully functional, but it shows sign of age through scuffs, dings, faded finishes, minimal upholstery defects, or visible repairs. Good — This vintage item remains fully functional, but it shows sign of age through scuffs, dings, faded finishes, minimal upholstery defects, or visible repairs.', 5000, 3),
	--Ancient Pottery--
('Euphronios Sarpedon krater God Hermes Vase Ancient Greek Pottery Ceramic Copy','New: A brand-new, unused, unopened, undamaged item in its original packaging (where packaging is applicable). Packaging should be the same as what is found in a retail store, unless the item is handmade or was packaged by the manufacturer in non-retail packaging, such as an unprinted box or plastic bag.', 4700,3),
('Geometric Krater 16cm,Ancient Greek Pottery Vase','A brand-new, unused, unopened, undamaged item in its original packaging (where packaging is applicable). Packaging should be the same as what is found in a retail store, unless the item is handmade or was packaged by the manufacturer in non-retail packaging, such as an unprinted box or plastic bag.', 8000,3),
('Minoan Vase Ceramic Pottery Painting Octopus Ancient Greek Crete Knossos',' A brand-new, unused, unopened, undamaged item in its original packaging (where packaging is applicable). Packaging should be the same as what is found in a retail store, unless the item is handmade or was packaged by the manufacturer in non-retail packaging, such as an unprinted box or plastic bag',3000,3),
('Dionysus Satyr Death of Orpheus Krater Vase Ancient Greek Pottery Museum Copy','Handmade:	Yes. Time Period Manufactured:	2020-NowSize:	Large	Country/Region of Manufacture:	Greece. Material:Ceramic, Clay	Featured Refinements:	Greek VaseBrand:	Handmade	Color:	MulticolorTheme:	Greek	Item Model Number:	K32Type:	Vase', 2000,3),
('Dionysus Satyr Death of Orpheus Krater Vase Ancient Greek Pottery Museum Copy','Handmade:	Yes. Time Period Manufactured:	2020-NowSize:	Large	Country/Region of Manufacture:	Greece. Material:Ceramic, Clay	Featured Refinements:	Greek VaseBrand:	Handmade	Color:	MulticolorTheme:	Greek	Item Model Number:	K32Type:	Vase', 2000,3),
	--Ancient Clock--
('STAR WORK Glass 30 cm Battery Operated Non-Ticking Silent Classic Quartz Easy to Read Wall Clock','Non-Ticking Silent Wall Clock: A silent quartz sweep continuous-movement clock motor ensures accurate time keeping and absolutely quiet working or sleeping environment. Wall clocks are perfect for adding artful appeal to your wall. Perfect for bedroom,school,office,living room,kitchen or commercial applications.Classic clock is a perfect gift for housewarmings, Christmas, birthdays, weddings or any special occasion.', 5000,3),
('Amazon Brand - Solimo 12-inch Wall Clock - Classic Roulette','Dial size: 12 inches in diameterMaterial of the frame: Plastic. Material of the transparent face: GlassBig, clear representation of the numbers on the clockMakes no sound while tracking time, sweep movement. Ideal for living room, bedroom & offices. Pack contents: 1 Wall Clock, 1 AA battery. Ebros Ancient Egyptian Bastet Table Clock Statue 6.75" Long with Roman Numerals',2000,3),
('Egyptian Winged Isis Clock, Fine Ancient Egyptian Statues','Egyptian Winged Isis Clock Figurine :   Beautiful Hand-made and Painted Figurine of Winged Isis with Quartz Alarm Clock (1 AA Battery Included). Product Details. Title: "Egyptian Winged Isis Clock Figurine".Size: 5" Wide, 4" Tall, 1.35" DeeoWeight: 7 Oz.Origin: Hand Made and Painted in Egypt (Year: 2005). Condition: Brand New Item, Hand-Painted Risen in Mint Condition. Comes in the Original box shown and packaging.', 3000,3),
('Vintage Farmhouse Kitchen Wall Clocks','This is a retro styled analog wall clock made from wood. This clock will add charm to any room in your home. There is a plastic shell casing behind the clock for batteries. Only one AA battery is required for this clock ( not included ). This vintage wall clock can be a good gift at housewarmings, weddings, and social gatherings.',1500,3),
('New Vintage Wooden Table Clock Bedroom','Bedside Snooze Alarm Clock wood Retro Desktop Clocks Home Decoration Desk Table Watch. New Vintage Wooden Table Clock Bedroom Bedside Snooze Alarm Clock wood Retro Desktop Clocks Home Decoration Desk Table Watch. Name: Wooden Alarm Clock. Style: European, American, casual. Appearance: Tower shape. Dial material: metal. Clock color: wine red. Applicable places: living room, bedroom, study room, office, kitchen', 1900, 3),
	--Ancient Weapons--
('European Swords & Daggers, Pre-1700 - ENGLISH HUNTING HANGER, 2ND HALF 17TH C', 'Featuring iron hilt with down-turned pierced shell guard on the obverse, single reversescroll quillon, and knucklebow attaching through a small hole in the capstan pommel with button; remains ofengraved decoration on pommel. Tapering cylindrical one-piece horn grip with iron base ferrule. Curved 23″ single-edged blade with broad full-length fuller (point slightly rounded). Blade engraved on the upper half with scrolling floral decoration.', 1100,3),
('ENGLISH PLUG BAYONET BY JOHN HATHAWAY, CA. 1690','Featuring tapering 11 ½” single-edged wedge-section blade, double-edged for the last 51/4″. The forte is deeply stamped on one side with the Blazing Star mark assigned to John Hathaway by the Worshipful Company of Cutlers of London on September 26, 1689 and also an unidentified King’s Head mark (KH18 in R.D.C. Evans’ “The Plug Bayonet”). While the King’s Head was a mark used by Solingen makers Weyersberg and Wundes',2000,3),
('FRENCH AND INDIAN WARS ERA SPIKED TOMAHAWK','Classic fighting spike ax of the Iroquois Federation. Original untouched example featuring a 10 inch hand-forged head with elliptical eye; original handle showing incised lines and inactive worm holes. This French and Indian Wars era tomahawk was from the famous Robert Wheeler Collection.  Mr. Wheeler was a renowned author and expert on Revolutionary War weaponry', 2000,3),
('GOLD HANDLED CIVIL WAR PRESENTATION CANE OF COLONEL WOUNDED IN ACTION','Presentation cane with hardwood shaft surmounted by a hallmarked gold cap inscribed in script: “Presented /To/Col. J.W. Jenkens/by 31st Iowa/Infty.” Overall length 32 ½”. The cane has a modern rubber tip, mild marks and scratches along the shaft, and some dents and light scratches on the gold handle. He died in Kansas City on June 24th, 1903, reportedly hastened by injuries sustained when struck with a club during a robbery.', 900, 3),
	--Ancient Books--
('1845 Rare Book bound by the Monastery Hill bindery - REYNARD THE FOX. Medieval Fables.', 'Attractive, rare and beautiful edition of REYNARD THE FOX. A renowned Apologue of the Middle Age, reproduced in Rhyme... Reynard the Fox is a literary cycle of medieval allegorical Dutch, English, French and German fables. The first extant versions of the cycle date from the second half of the 12th century. The genre is very popular throughout the Late Middle Ages, and in chapbook form throughout the Early Modern period.', 3500,3),
('1869 Rare Victorian Book - DAVID COPPERFIELD by Charles Dickens Illustrated by Browne.','A nice early edition of David Copperfield. Published by Chapman and Hall (193, Piccadilly). The Personal History of David Copperfield is a novel in the bildungsroman genre by Charles Dickens, narrated by the eponymous David Copperfield, detailing his adventures in his journey from infancy to maturity. It was first published as a serial in 1849–50, and as a book in 1850.',1300,3),
('1870 Rare Book - The LAMPLIGHTER by Maria Susanna Cummins.','Rare and nice early edition of The Lamplighter -- a sentimental novel written by Maria Susanna Cummins and published in 1854, and a best-selling novel of its era. The Lamplighter tells the story of Gertrude Flint, an abandoned and mistreated orphan rescued at the age of eight by Trueman Flint, a lamplighter, from her abusive guardian, Nan Grant. Gertrude is lovingly raised and taught virtues and religious faith. She becomes a moralistic woman.', 900,3),
('1885 First Edition - CONJURER Dick or, The Adventures of a Young WIZARD by Professor Hoffmann.','Scarce and attractive First edition of Conjuror Dick; or, The adventures of a young wizard -- a fictional book by Angelo John Lewis (Professor Hoffmann) published in 1885. It tells the fictional life story of a boy magician name Dick Hazard and his travels and adventures, in the company of a professional exhibitor as his assistant"', 3500, 3),
('1900 Rare PALMISTRY Book - CHEIRO LANGUAGE OF THE HAND with reproductions of Famous Hands.','Attractive and rare edition of Cheiro Language of the Hand. Cheiro had a wide following of famous European and American clients during the late 19th and early 20th centuries. He read palms and told the fortunes of famous celebrities like Mark Twain, W. T. Stead, Sarah Bernhardt, Mata Hari, Oscar Wilde, Grover Cleveland, Thomas Edison, the Prince of Wales, General Kitchener, William Ewart Gladstone, and Joseph Chamberlain.', 1400,3),

--FASHION--
	--Bracelet--
('Medical Alert Bracelet','A stunning medical alert bracelet with the medical symbol in black. Choose from 18 or 21cm in length with complimentary laser engraving in an easy to read font. I am hypoallergenic, non-tarnishing surgical stainless steel. A sturdy, allergy-free, waterproof metal that is corrosion-free and incredibly durable, making me perfect for everyday wear. I am easy to maintain; we have put together this easy to follow cleaning guide for you.', 550,4),
('Cherish Cuff Bracelet: I can and I will','Approx Length: 16cm adjustable cuff bracelet; this will fit most wrist sizes, children to men and women. Our cuff bracelets are made from a sturdy, anti-tarnishing, allergy-free and waterproof metal that is perfect for everyday wear. I am easy to maintain; we have put together this easy to follow cleaning guide for you. By clicking this link, you will be able to see how easy our pieces are to clean.', 220, 4),
('Jessica Bangle','The Jessica bangle fits from approximately 55mm to a 70mm size wrist, with a simple squeeze of the bangle. The Jessica bangle has a classic 10mm knot. A 5mm solid ball is highlighted on the end of each side to finish off this gorgeous style that is our Jessica bangle. I am hypoallergenic, non-tarnishing surgical stainless steel. A sturdy, allergy-free, waterproof metal that is corrosion-free and incredibly durable, making me perfect for everyday wear', 220,4),
('Medical Alert Bracelet','A stunni ng medical alert bracelet with the medical symbol in black. Choose from 18 or 21cm in length with complimentary laser engraving in an easy to read font.I am hypoallergenic, non-tarnishing surgical stainless steel. A sturdy, allergy-free, waterproof metal that is corrosion-free and incredibly durable, making me perfect for everyday wear. I am easy to maintain; we have put together this easy to follow cleaning guide for you.',550,4),
('Medical Alert Bracelet','A stunning medical alert bracelet with the medical symbol in black. Choose from 18 or 21cm in length with complimentary laser engraving in an easy to read font. I am hypoallergenic, non-tarnishing surgical stainless steel. A sturdy, allergy-free, waterproof metal that is corrosion-free and incredibly durable, making me perfect for everyday wear. I am easy to maintain; we have put together this easy to follow cleaning guide for you.', 800,4),
	--Necklace--
('Pave Butterfly Initial Choker','Gold vermeil choker. Lobster clasp closure. Butterfly and initial charms. Cubic zirconia accents. Measures approx 30 cm in length with a 8 cm extender. Gold vermeil choker. Lobster clasp closure. Butterfly and initial charms. Cubic zirconia accents. Measures approx 30 cm in length with a 8 cm extender. 14k gold plated necklace. Lobster clasp closure. Curb chain. Swarovski pearl accents. Measures approx 38 cm in length with a 5 cm chain extender.', 200,4),
('18kt yellow gold Teeny Tiny Rabbit pendant necklace', '18kt yellow gold Teeny Tiny Rabbit pendant necklace. Hop into the new season. And by that we mean in this 18kt yellow gold Teeny Tiny Rabbit pendant necklace from Alex Monroe. How adorable. Let us handle the legwork. Delivery duties are included in the item price when shipping to all EU countries plus The United Kingdom, USA, Canada, China Mainland, Australia, New Zealand, Puerto Rico, Switzerland, Singapore, Republic Of Korea, Kuwait, Mexico, Qatar, India.', 600,4),
('Best Yet To Come heart pendant necklace','Brinker & Eliza-Best Yet To Come heart pendant necklace. Brinker & Eliza necklace is a reassuring reminder that The Best Is Yet To Come. Cast from gold-tone brass chain links, its punctuated with a heart-shaped pendant thats oh-so-romantic. Treat yourself. The model is also styled with: GANNI high-rise wide-leg trousers, GANNI wrap-detail blazer jacket, Jil Sander ball accent thong sandals, REMAIN Gere ribbed-knit vest top.',100,4),
('Gucci-GG sterling silver necklace','GG sterling silver necklace-Calling all Gucci aficionados. This sterling silver necklace has a burnished antique effect that makes it look as though its been passed down for generations. Its made to be treasured. Highlights sterling silver , lobster claw fastening, logo pendant, antique effect. Made in Italy. This sterling silver necklace has a burnished antique effect that makes it look as though its been passed down for generations. Its made to be treasured.',200,4),
('Saint Laurent-Curb chain necklace','Your look could be off-the chain. All you need is this silver-tone metal curb chain necklace from Saint Laurent. It features an embossed logo and a clasp fastening. And a serious dose of cool. Made in Italy. Your look could be off-the chain. All you need is this silver-tone metal curb chain necklace from Saint Laurent. It features an embossed logo and a clasp fastening. And a serious dose of cool.', 600,4),
('Versace-Greca Medusa detail necklace','In dire need of causing a serious visual impression? The moment you decided to throw on this gold-tone Greca Medusa detail necklace from Versace thats precisely what you did. Evidently so. Highlights gold-tone, brass, signature Greca detailing. Medusa head motif, lobster claw fastening, polished finish. Made in Italy', 400,4),
	--Fashion Shoes--
('Dolce & Gabbana-City leopard-print ankle boots','Dolce & Gabbana takes inspiration from snowy-day style to deliver these ankle boots. Boasting a padded construction, the pair is adorned with an all-over leopard print in line with the brand penchant for bold designs. The model is also styled with: Dolce & Gabbana large quilted Devotion shoulder bag, Wolford x Amina Muaddi sleeveless catsuit, Aleksandre Akhalkatsishvili faux-leather belted padded coat.',800,4),
('Balmain B-Bold high-top sneakers','Balmain signature opulent style is celebrated in this version of the B-Bold sneakers. The high-top silhouette is updated with an embossed crocodile effect and two logo-embossed straps at the upper. Highlights: black,calf leather,round toe,embossed crocodile effect,sock-style ankle,logo-embossed straps,front touch-strap fastening,ankle-length,pull-tab at the heel,platform sole', 900,4),
('Alexander McQueen Kids Oversized low-top sneakers','Alexander McQueen extends its signature Oversized shoe silhouette to its kidswear line with this all-black iteration. Crafted from patent leather and boasting a high-shine finish, these sneakers lace up at the front and sit atop a familiar chunky rubber sole for a voluminous design. Highlights: black,leather,high-shine finish,chunky rubber sole,front lace-up fastening,round toe,branded heel counter. Made in Italy',500,4),
('Nike Kids Air Max 720 sneakers','Supplied by a premier sneaker marketplace dealing with unworn, already sold out, in demand rarities. Each product is rigorously inspected by experienced experts guaranteeing authenticity. The best part of childhood is being able to jump about, do whatever you please and have fun. Which makes these black Air Max 720 sneakers from Nike the perfect pick for providing a comfortable low-top silhouette to any event. Adventure awaits.',100,4),
('MACH & MACH Diamond of Elizabeth transparent pumps','Georgian footwear brand Mach & Mach creates eye-catching silhouettes for statement looks. Crafted in a transparent black shade, the Diamond of Elizabeth pumps are adorned with glistening crystals over their pointed toes and boast a pearl chain that wraps around the ankle.', 100,4),
('JW Anderson Chain loafer mules','First seen in the AW20 runway show, these loafers from JW Anderson combine both style and comfort. Crafted from white leather, the slip-on pair is accented with a chunky chain-link detail in a polished tonal design. Highlights: white,leather,chain-link detailing,round toe,slip-on style,branded insole,cork sole,flat rubber sole',500,4),
	--Dress--
('Jacquemus-Valdu sleeveless maxi dress','With a cut out back and tonal strap detailing, the Valdu dress embodies two key features of Jacquemus visual identity. Presented in classic beige, the piece is discreetly punctuated by gold-tone hardware. The model is 1.76 m wearing size 36 (FR). The model is also styled with: BY FAR Fida 100mm leather sandals, Jacquemus Le Chiquito Moyen mini bag. Washing instructions: Dry Clean Only',900,4),
('Fendi-FF Karligraphy satin dress','This slip dress from Fendi is crafted from satin whose lustrous finish is highlighted by a fluid two-layer design. It is finished with FF Karligraphy openwork embroidery that showcases the Italian powerhouse rich history. Outer: Silk 100%, Viscose 100%. The model is 1.77 m wearing size 40', 200,4),
('GANNI - Leather mini shirtdress','GANNI transforms the traditional shirtdress by crafting it using leather. The white contrast stitching adds a contemporary appeal, while the self-tie belt cinches the waist of the brand signature boxy shape, conveyed through the short sleeves. POSITIVELY CONSCIOUS: This brand measures the impact of every item they produce and supplies a Carbon Neutral Certification with each purchase, which measures the environmental impact of production and shows that they have covered the cost of making the carbon footprint neutral.',600,4),
('Cecilie Bahnsen-Holly off-shoulder midi dress','Known for adding a twist to Scandinavian minimalism, Cecile Bahnsen plays with details and proportions. Crafted from recycled materials in a versatile light-grey hue, the Holly dress is a prime example. It is cut to an empire line silhouette with an ankle-grazing flared skirt, framed by thin spaghetti straps and long puff sleeves that drape from below the shoulder, enhancing the voluminous shape.', 900,4),
('There Was One-Mid-length spaghetti-strap slip dress','Crafted in a black satin weave, this dress from There Was One was designed to transcend the seasons. Finished with a square neck and spaghetti straps, the mid-length silhouette is both elegant and timeless. This garment contains materials certified by the Forest Stewardship Council (FSC), which ensure that the wood used comes from responsibly managed forests.', 400,4),
('Versace Greca logo-print minidress','Highlights: deep-orange/royal-blue, wool-silk blend,signature Greca-pattern print,round neck,short sleeves,fitted waistline. Made in Italy. The model is 1.78 m wearing size 40 (IT). The model is also styled with: Off-White Arrows pendant earrings, Balmain B-Buzz baguette bag, Jil Sander square-toe 95mm knee-high boots.', 400,4),
	--Jacket--
('Moncler-Avoine cropped padded jacket','Known for their padded down jackets, Italian fashion house Moncler was founded in 1952 and started life creating quilted sleeping bags and tents. Presented in a grey hue, this Avoine cropped jacket is detailed with the label signature logo patch to the outer left sleeve. The model is also styled with: Totême square-toe Chelsea boots, Saint Laurent diamond-quilted scarf, OpéraSPORT Claude logo print T-shirt.',500,4),
('Frankie Shop - Olympia oversized single-breasted blazer','We might have just found your dream jacket. Made from faux leather and cut for an oversized fit, this Olympia blazer buttons up at the front with a single-breasted design and boasts notch lapels for a sleek yet relaxed look. Outerwear perfection. The model is also styled with: Frankie Shop Manon high-waisted shorts, Lemaire open-toe flat mules, LVIR contrast-stitch long-sleeve shirt, Jil Sander drawstring leather mini bag.', 400,4),
('Fendi Scribble-detail logo down jacket','Scribble-detail logo down jacket - Highlights: black,down-feather filling,logo print to the front,logo print to the rear,abstract pattern print,high neck,front zip fastening,long sleeves. Made in Italy. Outer: Polyester 100%. Lining: Polyester 100%, Polyamide 100%, Down 75%, Feather 25%. The model is 1.85 m wearing size L', 600,4),
('New Season Jacquemus - Zipped shirt jacket','Highlights: black, cotton-virgin wool blend ,classic collar, front zip fastening, long sleeves, buttoned cuffs, two button-fastening chest pockets, curved hem. Composition: Outer: Virgin Wool 80%, Polyamide 20%. Lining: Cotton 55%, Polyester 45%. The model is also styled with: 1017 ALYX 9SM two-tone chain-link necklace, Jacquemus La Chemise floral-print shirt, Bottega Veneta Eyewear geometric oversized-frame sunglasses, Bonastre Bon Bon leather shoulder bag, A-COLD-WALL* x Dr.',700,4),
('Moncler Enfant - Ercan printed-logo down jacket','Designed in an off-white hue, this Ercan jacket from Moncler has been constructed with a feather down interior. Boasting an oversized logo print to the rear, it features two side zip-fastening pockets and a contrasting logo patch to the chest.Composition: Outer: Polyamide 100%. Lining: Feather Down 100%, Polyamide 100%',600,4),
('Moncler Enfant - New Maya puffer jacket','Moncler Enfant New Maya puffer jacket provides comfort in cold weather thanks to its padded design and a hood too. The model is 1.07 m wearing size 10 (yrs). The model is also styled with: Bonpoint double-breasted hooded trench coat, Moncler Enfant logo-print cotton sweatshirt, Moncler Enfant logo-patch pompom beanie, MM6 MAISON MARGIELA KIDS loose-fit jeans, UGG Kids fluffy yeah slides.',600,4),
	--Jeans--
('AMBUSH-REGULAR FIT DENIM PANTS BLU WASHED NO CO','Composition: Cotton 100%, Leather 100%. Composition: Cotton 100%, Leather 100%. The model is 1.86 m wearing size 32 (Waist). The model is also styled with: AMBUSH turtleneck jersey T-shirt, Eytys Luciano Western-style boots, Givenchy Antigona U camera bag, Emanuele Bicocchi Stone signet ring, Wacko Maria leopard knit cardigan.',200,4),
('ERL Cropped straight-leg jeans','Highlights: washed blue, cottons, tone washed, whiskering effect at the thighs, belt loops, front button fastening, straight leg. Made in Italy. The model is 1.78 m wearing size M. The model is also styled with: Tibi turtleneck wool knit top, Karen Wazen Kaia oversized-frame sunglasses, ERL faux-fur single-breasted jacket, Yuzefi Bom tote bag, Off-White arrow earrings.',200,4)
('Ralph Lauren Kids Eldridge skinny-fit jeans','Polo Ralph Lauren is the master of all things smart-meets-casual. These Elridge jeans are the prime example, thanks to their comfortable stretch cotton blend and skinny-fit design. Composition: Cotton 92%, Elastane 8%. Washing instructions. Machine Wash', 100,4),
('Maison Margiela-Distressed straight-leg jeans','Maison Margiela may look relatively tame but they are anything but basic. A little baggy, they have a straight-leg shape and are slashed at the sides to reveal a little skin. Oo er. Featuring a button and zip fly, belt loops, a five pocket design, a distressed detail and a high rise.', 400,4),
('Valentino x Levi’s bootcut high-rise jeans','Combining denim excellence with Italian luxury, these Valentino x Levi’s high-rise jeans embody the best of the two brands. Designed with a flattering bootcut, the pair stands out in this collaboration. The model is 1.78 m wearing size 28 (in). The model is also styled with: Alexander McQueen oversized sole sneakers, Bottega Veneta The Triangle tonal-design tote bag.',500,4),
	--Watch--
('MAD Paris x 1017 ALYX 9SM pre-owned customised Royal Oak','Fine watch specialist MAD Paris presents a new take on a classic. The customised professionals have partnered up with Matthew M. Williams, the creative force behind 1017 ALYX 9SM, to welcome this Audemars Piguet Royal Oak to the latest collection. Crafted from 18kt gold, the sleek piece combines both a timeless model with a contemporary finish the label is known for.',100,4),
('Rolex 2021 unworn Cosmograph Daytona 40mm','Swiss luxury timepiece specialist Rolex is known for presenting sports-influenced designs that will withstand the test of time. A nod to the car racing that took place every year on Daytona Beach, this 2021 unworn Cosmograph Daytona 40mm model was born out of the love of all things motor, complete with a tachymeter scale on the outer ring and a telemeter on the inner as a tribute to the fast life of watches and cars. ',100,4),
('Briston Watches Streamliner Ad-Venture 44mm','French watchmakers Briston were born out of a rich inspiration from British sports. Unique in style with a contemporary finish, the Streamliner Ad-Venture 44mm is finished with a digital dial to offer both a sleek yet retro-inspired design for modern wear.',300,4),
('Zadig&Voltaire Montre Butterfly 40mm watch','Silver-tone stainless steel and glass Montre Butterfly 40mm watch from Zadig & Voltaire featuring micro stud details, a butterfly print and an adjustable fit. Composition: Stainless Steel, Glass',200,4),
('Tommy Hilfiger Contrast bezel quartz 38mm','Tommy Hilfiger has been the leading brand when it comes to American heritage with an effortless air. Since 1985, each collection presents an opportunity to welcome timeless and classic designs, like this contrast bezel quartz 38mm that features a multifunction dial for appeal.', 150,4),

--ELECTRONICS--
	--Phone--
('360° Car Air Vent Phone Holder', 'Holder base rotates 360° for omnidirectional functionality- Holds smartphone devices in place.- Helps provide convenience when it comes to using electronic devices while driving. Provides additional safety while driving and easily attaches onto car consoles. Suitable for phones with screen sizes between 4 - 6 inches. Modern design complemented by sturdy grip that prevents slippage. Made from lightweight and durable material. Quantity : 1 piece. Size : 6.5 x 5.3 x 11 cm.', 30,5),
('Apple AirPods (2nd Generation)','About this item: Automatically on, automatically connected. Easy setup for all your Apple devices. Quick access to Siri by saying “Hey Siri”. Double-tap to play or skip forward', 100,5),
('Ailun Glass Screen Protector Compatible for iPhone 11/iPhone XR, 6.1 Inch 3 Pack Tempered Glass','About this item: WORKS FOR iPhone 11/iPhone XR (2019/2018 release) 6.1 Inch display ,0.33mm tempered glass screen protector. Featuring maximum protection from scratches, scrapes, and bumps.. Specialty: Due to the rounded design of the iPhone 11/XR and to enhance compatibility with most cases, the Tempered glass does not cover the entire screen. HD ultra-clear 99.99% touch-screen accurate.',50,5),
('iPhone Charger','About this item: DURABLE MATERIAL: Phone cable With 8000+times bend lifespan and integrated molding process, the nylon braided jacket is super smooth and comfortable,more durable than standard Phone charger cord. PERFECT LENGTHS: Perfect 6feet extra long phone charger cable free up your charging time, no more being stuck to wall socket, ideal for using at home, in car and office.',20,5),
('Xperia PRO Portable High Speed Transmission Device & Smartphone with HDMI Input, 6.5" 4K HDR OLED Screen, 5G mmWave','About this item. World’s first smartphone w/ HDMI connectivity to capable cameras. Fast reliable signal w/ unique 360-degree 4-way 5G mmWave antenna. 6.5” 4K HDR 21:9 OLED display doubles as camera monitor via HDMI. Livestream w/ services like YouTube using HDMI connected camera. Fast, easy file transfer w/ USB-C and FTP upload via 5G connectivity',600,5),
	--Computer--
('Lenovo IdeaPad', '1 14 14.0" Laptop, 14.0" HD (1366 x 768) Display, Intel Celeron N4020 Processor, 4GB DDR4 RAM, 64 GB SSD Storage, Intel UHD Graphics 600, Win 10 in S Mode, 81VU0079US, Ice Blue. This everyday laptop is powered by an Intel Celeron N4020 processor, 4GB DDR4 RAM, and 64 GB M.2 PCIe SSD storage. This everyday laptop is powered by an Intel Celeron N4020 processor, 4GB DDR4 RAM, and 64 GB M.2 PCIe SSD storage', 300,5),
('Seagate Portable 2TB External Hard Drive Portable HDD – USB 3.0 for PC, Mac, PS4, & Xbox - 1-Year Rescue Service','Easily store and access 2TB to content on the go with the Seagate Portable Drive, a USB external hard drive. Designed to work with Windows or Mac computers, this external hard drive makes backup a snap just drag and drop. To get set up, connect the portable hard drive to a computer for automatic recognition no software required',50,5),
('Logitech BRIO Ultra HD Webcam for Video Conferencing, Recording, and Streaming - Black','Spectacular video quality: A premium glass lens, 4k image sensor, high dynamic range (Hdr), and autofocus deliver beautiful, true to life video.Look great in any light: Right light 3 automatically adjusts exposure and contrast to compensate for glare and backlighting. Supports multiple connection types, including USB 2.0 type a and USB 3.0 type a and C connections.', 200,5),
('BENGOO G9000 Stereo Gaming Headset',' For PS4 PC Xbox One PS5 Controller, Noise Cancelling Over Ear Headphones with Mic, LED Light, Bass Surround, Soft Memory Earmuffs for Laptop Mac Nintendo NES Games. 【Multi-Platform Compatible】Support PlayStation 4, New Xbox One, PC, Nintendo 3DS, Laptop, PSP, Tablet, iPad, Computer, Mobile Phone. Please note you need an extra Microsoft Adapter (Not Included) when connect with an old version Xbox One controller.',30,5),
	--Electronice device--
('Electric Chopper','Four S-shaped blades allow for omnidirectional slicing and dicing for quick and evenly processed food. It can also be used with beans, nuts, and other foods that wish to process. Simple one-touch operation. Powerful and silent motor helps save time when it comes to ingredient preparation. The grinder body is made of food-grade plastic that is easy-to-clean and easy-to-store. Suitable for usage in residential areas, kitchens and anywhere else as needed.',30,5),
('CCTV Camera','1080P HD indoor, plug-in security camera with motion detection and two way audio that lets you monitor the inside of your home day and night. Get alerts on your smartphone whenever motion is detected or customize motion detection zones so you can see what matters most. Store events conveniently and securely in the cloud with a 30-day free trial of the Blink Subscription Plan or locally with the Sync Module 2 and a USB flash drive (USB sold separately).',60,5),
('GreaterGoods Digital Food Kitchen Scale, Multifunction Scale Measures in Grams and Ounces','A Premium Choice: Between the design and quality, this kitchen scale is going to last and function at an impeccable level. Your cooking just got ten times easier. Fresh Features: All of the qualities you need and expect in a kitchen scale: readings down to the gram, an eleven pound capacity, and easy to read display. What more could you want?. ', 15,5),
('Power Blender & Processor','The 3-in-1 blender that crushes, food processes, and makes dough. Smart TORQUE is designed to power through heavy loads without stalling or the need to stir or shake. Variable speed control. Start slow and ramp up as needed for precision chopping and mixing. Power Blender & Processor Pitcher: crush, chop, and make dough conveniently in one pitcher.', 100,5),
('Heater','2 in 1 heater fan: This ceramic heater provides two heat levels, 1500W or 750W and one cool air fan, you can use it both for winter and summer. Thermostat control of the heater will turn the heater off when it reaches a preset temperature and turn the heater back on when the temperature dips below the thermostat setting. It will cycle on and off. Adjust the setting of thermostat from 0℉ to 158℉ to keep room comfortable', 45,5),
('Honeywell HT-900 TurboForce Air Circulator Fan Black, Small','Small fan for table or floor: The Honeywell turbo force air circulator fan has 3 speeds & a 90 degree pivoting head. This quiet fan is compact enough for on a table or wall mount & powerful enough to help provide comfortable cooling in small-medium rooms.', 15,5),

--COLLECTION--
	--Wine--
('Apothic Red Blend Winemaker Blend Wine 2019 - 750 ML','A masterful red blend wine featuring rich Zinfandel, smooth Merlot, flavorful Syrah, and bold Cabernet Sauvignon. These unique elements come together to create a red blend with layers of dark red fruit complemented by hints of vanilla and mocha.',10,6),
('Juggernaut Hillside Cabernet Sauvignon 2019 - 750 ML','French oak beautifully transforms intense mountain fruit into a wine with uncommon richness, yet smooth and luxurious texture. Juggernaut Hillside Cabernet is a wine that is fierce, brave, and delicious. Rich and intense with a complex character and smooth finish. Luxurious texture with black currants and vanilla. Aroma of licorice and blackberry.',15,6),
('Bogle Vineyards Cabernet Sauvignon 2018 - 750 ML','This complex and developed fruit is showcased in the glass with first impressions of dried cherries, tobacco leaf and Madagascar vanilla. Wrapping the palate in richness, the full bodied flavors of cherry and plum compote resonate, followed by touches of tanned leather and dark chocolate. Aging in one-year old American oak for 12 months creates a finish with ample and enduring tannins, and tones of sweet tobacco smoke and spicy oak.',20,6), 
('Decoy Sonoma Cabernet Sauvignon 2019 - 750 ML','Displaying the lushness and balance that define great Sonoma County Cabernet Sauvignon, this inviting wine features layers of blackberry and black cherry, alongwith notes of mocha, star anise and spearmint. On the palate, the juicy, bright fruitflavors are framed by rich, refined tannins that carry the wine to a satisfying finish. Blend: 88% Cabernet Sauvignon, 8% Merlot, 2% Petite Verdot, 1% Petit Sirah, 1% Cabernet France', 15, 6),
('Orin Swift Cellars Abstract Wine 2019 - 750 ML','As soon as a glass is poured, aromatic notes of Luxardo cherries, ripe black plums and raspberries billow, with intricate hints of coffee, mocha and caramel in the background. The entry is expansive with dark briar fruits, cola and cocoa with tannins that are soft and dusty. The wine finishes with a hint of wild cherry and a lingering sweet oak presence.',30,6),
	--Stamp--
('American Coin Treasures 40 U.S. Postage Stamps from The 1910s, 1920s, 1930s and 1940s','Stamps from 4 decades: Mint US Postage Stamps. All stamps guaranteed to be over 65 years old. Comes wrapped in plastic with cardboard protector. Includes A Certificate of Authenticity, 1 Year Manufacturers Warranty.',10,6),
('Military Working Dogs U.S. Postage Stamps Sheet of 20 Forever Postage Stamps Scott 4508B','Available at a lower price from other sellers that may not offer free Prime shipping. These new red, white and blue forever postage stamps featuring military working dogs are designed to honor the nation’s brave and loyal canines. The sheet of 20 stamps features artist renderings of four breeds commonly used as military working dogs: German shepherd, Dutch shepherd, Labrador retriever and Belgian Malinois',18,6),
('Christmas Carols - USPS Forever Stamps Book of 20 - New 2017 Release','Forever stamps are always equal to the USPS first-class one ounce letter rate. Double-sided booklet of 20 Forever stamps. Perfect for holiday mailings, gifts & more. Images from popular holiday songs. Great for christmas cards, holiday cards, and more', 15,6),
('2018 Madonna and Child by Bachiacca Forever Postage Stamps','This "Madonna and Child by Bachiacca" forever postage stamp was released in October 2018. This forever postage stamp features a detail of Bachiacca’s oil-and-gold-on-panel painting “Madonna and Child,” which dates from the early 1520s, showing the Christ child clutching a bouquet of jasmine, a symbol of divine love, alongside the Virgin Mary’s profile, left shoulder and right hand.',25,6),
('Celebration Boutonniere USPS Forever Stamps Sheet of 20 - New Stamp Issued 2017','This beautiful stamp can be used on RSVP envelopes often enclosed with wedding invitations, party invitations, thank-you notes, announcements, or any other correspondence. Celebration Boutonniere is similar in design to the Celebration Corsage Forever stamp, and the two form a natural pair.', 25,6),
	--Coin--
('2021 American Silver Eagle 1 oz Type 2 Coin In U.S. Mint Box $1 Brilliant Uncirculated US Mint','2021 AMERICAN SILVER EAGLE $1 TYPE 2 (NO MINT MARK). U.S MINT BOX (no COA). BU (Brilliant Uncirculated). - NOT A PROOF OR BURNISHED EAGLE. Great addition to any collection,Great gift for all encapsulated in air tite capsule to preserve the coin.', 45,6),
('U.S. Liberty Head (Barber) Nickels - 7 Coin Grab Bag', 'U.S. Liberty Head (Barber) Nickels. Composition: Copper Nickel; Diameter: 21mm. Most coins in the U.S. Liberty Head (Barber) Nickels grab bags are dated between 1899 and 1912. Coins all have readable dates and range from AG (Almost Good) to VG (Very Good). Perfect for gift giving',10,6),
('John Wick Prop Continental Hotel Collection Gold Coin','MATERIAL: Zinc Alloy, High Precision Manufacturing, Plating Procedures. CHARACTER: Thriller Movie John Wick Copslay Acccessory. SIZE: Coin Size: 1.5" in Diameter and 0.118" Thick; ONE PICE WEIGHT: 1.06oz; PACKAGE INCLUDES: 1*PC. DESIGN: 1, Obverse: Features a Lion in Stride with a Large Shield in the Background. "Ens Causa Sui" and “MMI” can be Read Along the Top and Bottom; 2"',10,6),
('CA 2021 Lot of (10) 1 oz Silver Canadian Maple Leaf Coins Brilliant Uncirculated with our Certificates of Authenticity by CoinFolio BU','Purity: .9999 Fine Silver. Diameter: 38 mm; Thickness: 3.29 mm. Metal Content: 1 Troy Ounce per Coin; Total: 10 Troy Ounces. You will receive ten coins per purchase inside the original Royal Canadian Mint acrylic tube. Stock Photo; Image is indicative of quality; Coins will come with ten certificates of authenticity', 100,6),
('10,000 Amazon Coins','Buy Amazon Coins and save on apps, games, and in-app items. 100 Amazon Coins are worth $1.00 to spend on apps, games, and in-app items. Coins you buy never expire. Use Amazon Coins on Fire tablets, Fire TV, and on any Android device through the Amazon Appstore. The purchase of Amazon Coins is not taxable; however, in select US States, applicable taxes will apply when Amazon Coins are used for purchase of digital goods.', 80,6),
	--Card--
('Pokemon Grass Collection','ULTIMATE GRASS COLLECTION - Unleashed the power of Grass. This collection contains the most powerful grass pokemon cards ever. Comes with 5 rare grass Pokémon cards and 1 grass ultra-rare pokemon card. ULTIMATE GRASS COLLECTION - Unleashed the power of Grass. This collection contains the most powerful grass pokemon cards ever. Comes with 5 rare grass Pokémon cards and 1 grass ultra-rare pokemon card.', 30,6),
('Yugioh Official Cards','Yugioh Official Cards Prismatic Art Collection Booster Box. 3 Prismatic Secret Rares. 8 Ultra Rares / 12 Super Rares. 27 Normal Parallel Rares. Konami Genuine Korean version (100% Original Items).', 10,6),
('NBA Basketball Hit Collection Gift Box & Collecting Guide','PACK OF 100 BASKETBALL CARDS: Each of our basketball card collections contain 100 high-quality cards that are a blend of New and Vintage that any NBA fan would love to have! Our massive collection of Basketball Trading Cards spans many years of NBA history and contains some of the best players to play the game.',30,6),
('I Know Collection Affirmation Cards','THE POWER OF MANIFESTATION -- If you truly believe in the power of manifestation, the Dreamers affirmation cards by I Know Collection are the right way to start nurturing self-confidence, positivity, and courage, leaving behind everything that keeps you from reaching your goals.', 20, 6),
('Hallmark All Occasion Handmade Boxed Set of Assorted Greeting Cards with Card Organizer ','Fun and festive boxed set contains everything you need to celebrate throughout the year: 24 greeting cards with coordinating envelopes and a storage box with dividers to keep cards neatly organized. Fun and festive boxed set contains everything you need to celebrate throughout the year: 24 greeting cards with coordinating envelopes and a storage box with dividers to keep cards neatly organized.', 25,6),


