USE AuctionOnline
GO

INSERT INTO Product_Categories VALUES 
('Art','Art.jpg'),
('Vehicle','Vehicle.jpg'),
('Antique','Antique.jpg'),
('Fashion','Fashion.jpg'),
('Electronics','Electronic.jpg'),
('Collection','Collection.jpg'),
('Sports','Sports.jpg'),
('Toys & Game','Toys&Game.jpg'),
('Beauty & Comestic','Beauty&Comestics.jpg')

SELECT * FROM Product_Categories
GO

INSERT INTO Sub_category VALUES
--Art category
('Oil Painting',1),
('Classic Painting',1),
('Art Photo',1),
--Vehicle
('Car',2),
('Boat',2),
('Plane',2),
--Antique
('Furniture Antiques',3),
('Ancient Pottery',3),
('Ancient Clock',3),
('Ancient Weapons',3),
('Ancient Books',3),
--Fashion
('Bracelet',4),
('Necklace',4),
('Fashion Shoes',4),
('Dress',4),
('Jacket',4),
('Jeans',4),
('Watch',4),
--Electronics
('Phone',5),
('Computer',5),
('Electronice device',5),
--Collection--
('Wine',6),
('Stamp',6),
('Coin',6),
('Card',6),
--Sports--
('Adidas',7),
('Nike',7),
('Accessories',7),
--Toys & Game--
('Dolls & Accessories',8),
('Puzzles',8),
('Arts & Crafts',8),
(' Building Toys',8),
--Beauty&Comestic--
('Make up',9),
('Skin Care',9),
('Hair Care',9),
('Foot, Hands, Nails Care',9)

SELECT * FROM Sub_category
GO
DELETE FROM Sub_category
INSERT INTO Products VALUES 
--ART--
	 --Oil Painting--
('Mona Lisa','Mona Lisa is one of the most famous oil paintings in the world. A 16th-century portrait painted in oil on a poplar panel in Florence by Leonardo da Vinci during the Italian Renaissance. The work is owned by the French Government and is currently on display at the Louvre in Paris, France as Portrait of Lisa Gherardini, wife of Francesco del Giocondo',15000,1),
('The Starry Night','Painted in June 1889, the painting depicts the scene outside the window of his hospital room in Saint-Rémy-de-Provence, southern France at night, although he painted the picture during the day through his mind. mind. The Starry Night is in the collection of the Museum of Modern Art in New York City, part of the Relics of Lillie P. Bliss, from 1941. The painting is one of van Gogh most famous works. , marking a decisive turning point towards greater creative freedom in his art.',6000 ,1),
('Girl with a Pearl Earring','The oil painting, born around 1665, has been especially noticed by art lovers since becoming the subject of the best-selling historical novel of the same name, published by writer Tracy Chevalier in 1999.Until now, art experts have not been able to decipher the origin of this oil painting, because there is not much information about the artist as well as the model in the picture. The painting is currently on display at the Mauritshuis museum in Den Haag, Netherlands.',35000 ,1),
('The Cafe Terrace on the Place de Forum','This is the first oil painting Van Gogh painted the starry sky as the background. One year after painting Cafe Terrace, Van Gogh continued painting Starry Night. In a letter to his brother Theo, Van Gogh reminded of the Cafe Terrace that he painted "the scene of the cafe on the sidewalk of the Forum Hotel, where we used to go" and "painted at night".', 20000,1),
('The Birth of Venus','Botticellis oil painting The Birth of Venus is the first full-length, non-religious nude image since antiquity. The painting was painted for Lorenzo de Medici. Venus appeared on the seashore in a giant seashell next to the wind god Zephyrus and Aura as a sign of the arrival of spring in this land.',12000 ,1),
('Les Demoiselles d’Avignon','Les Demoiselles d’Avignon became an iconic oil painting of the 20th century, breaking with tradition commonly found in Western painting, incorporating the African masks Picasso saw at the ethnomuseum. study in Paris. The women depicted in the painting are actually prostitutes in the brothel in Barcelona, the artist’s hometown.',25000,1),
('The Kiss','The painting The Kiss marks Gustav Klimt’s heyday from 1899-1919 when he often used gold leaf - a technique inspired by a 1903 trip to the Basilica di San Vitale in Ravenna, Italy, where he saw the famous Byzantine mosaics of the church.',20000,1),
	--Classic Painting--
('American Gothic','American Gothic is a painting by Grant Wood from the collection of the Art Institute of Chicago.The painting shows a farmer standing next to his aunt.Real-life samples from the author. It is one of the most familiar images in American art,and is parodyed by many.', 15000,1),
('A night full of stars','Starry Night is a painting by artist post-impressionist who Netherlands Vincent Van Gogh. Painted in June 1889, the painting depicts the scene outside the window of his hospital room in Saint-Rémy-de-Provence , southern France at night, although he painted the picture during the day through his mind.',10000,1),
('Whistler’s Mother', 'James Abbott McNeill Whistler painted the work in his London studio in 1871, and in it, the formality of portraiture becomes an essay in form. Whistler’s mother Anna is pictured as one of several elements locked into an arrangement of right angles.', 9000,1),
('The Kiss','The Kiss, Gustav Klimt’s fin-de-siècle portrayal of intimacy, is a mix of Symbolism and Vienna Jugendstil, the Austrian variant of Art Nouveau. Klimt depicts his subjects as mythical figures made modern by luxuriant surfaces of up-to-the moment graphic motifs.The Kiss, Gustav Klimt’s fin-de-siècle portrayal of intimacy, is a mix of Symbolism and Vienna Jugendstil, the Austrian variant of Art Nouveau. Klimt depicts his subjects as mythical figures made modern by luxuriant surfaces of up-to-the moment graphic motifs',7000,1),
('The Last Supper','The Last Supper is a famous fresco by Leonardo da Vinci . The work was composed between 1495 and 1498. The fresco is located in the banquet hall of the Monastery of Santa Maria in Milan .', 9000,1),
('Las Meninas','Las Meninas ( Spanish maid of honor or simply The ladies ) is a picture painted in 1656 by Diego Velázquez , painter top heyday Spain , located in the museum Museo del Prado in Madrid. Thanks to these unique features, "Las Meninas" has become one of the most widely analyzed works in Western painting .',13000,1),
	--Art Photo--
('Wild Horses','Horse Photography - Mountains Wanderlust Travel photography by Ingrid Beddoes Art Print Horse Photography - Mountains Wanderlust Travel photography by Ingrid Beddoes Art PrintHorse Photography - Mountains Wanderlust Travel photography by Ingrid Beddoes Art PrintHorse Photography', 10000,1),
('These Boots - Glitter Pink Art Print','Beautiful print. Loved the colors and details. Not s Glossy print but matte and perfect. Only issue I found was being able to find a frame for the print size. I ended up having my boyfriend make a custom frame for me because he is a carpenter.', 15000,1),
('Scottish Highland cattle on a farm','Close up portrait of Scottish Highland cattle on a farm. This photographic print leverages sophisticated digital technology to capture a level of detail that is absolutely stunning. The colors are vivid and pure. The high-quality archival paper, a favorite choice among professional photographers, has a refined luster quality.',18000,1),
('Tree in Field of Flowers','Tree in Field of Flowers by Mia Friedrich is a tranquil art painting print that uses pastel colors to capture a blooming tree in the midst of a field of white flowers. Tree in Field of Flowers by Mia Friedrich is a tranquil art painting print that uses pastel colors to capture a blooming tree in the midst of a field of white flowers.',20000,1),
('Elmer','Keep your furry and feathery friends close, whether they are a galloping stallion or a dog taking a selfie. Our gallery is here to turn empty walls into a cute and quirky display of animal art. Keep your furry and feathery friends close, whether they are a galloping stallion or a dog taking a selfie. Our gallery is here to turn empty walls into a cute and quirky display of animal art.',15000,1),

--VEHICLE--
	--Ferrari--
('Ferrari SF90 Stradale','The SF90 Stradale is a plug-in hybrid electric vehicle. With a maximum capacity of 986 horsepower, a maximum speed of 340km / h and the ability to accelerate from 0-100km / h in 2.5s. This is the most powerful production Ferrari car to date. With a completely new exterior design, the interior is full of technology.Hypercar SF90 Stradale launched in May 2019 deserves to be a masterpiece but has a fairly cheap price.', 500000,5),
('Ferrari F12 Berlinetta','This super car with a handsome and handsome appearance contains tremendous power inside it. Equipped with a 6.3L V12 engine with a maximum capacity of 730Hp/8250rpm, maximum torque of 690Nm/6000rpm; 7-speed dual-clutch transmission; The car accelerates to 100km/h in 3.1s.', 200000,5),
('Ferrari 812 Superfast','812 Superfast will debut at the upcoming Geneva show. With a worthy replacement for the elder F12, the Ferrari 812 Superfast uses a slightly larger engine, 6.5L V12 with a capacity of 789Hp, a terrible torque of 718Nm. The car accelerates to 100km / h in 2.9s, faster than even LaFerrari.Top speed 339km/h. Due to late birth, 812 Superfast is also equipped with many new technologies. At this point, the official price of this accelerated champion is available.', 340000, 5),
('Ferrari 488GTB','Perhaps Ferrari 488GTB is the Ferrari model with the most volume to Vietnam, about over 10 cars by the end of 2016, simply the price of Ferrari 488GTB is considered quite reasonable, about 17-20 billion in Vietnam.Perhaps Ferrari 488GTB is the Ferrari model with the most volume to Vietnam, about over 10 cars by the end of 2016, simply the price of Ferrari 488GTB is considered quite reasonable, about 17-20 billion in Vietnam', 260000,5),
	--Hyundai--
('Hyundai Palisade','The Hyundai Palisade is a full-size SUV manufactured by Hyundai Motor (Korea). The car was first unveiled at the Los Angeles Auto Show in November 2018. Palisade is the flagship SUV of the Hyundai brand, the "elder" of Hyundai Santafe.In May 2019, the first Hyundai Palisade appeared in Vietnam in the form of original imports from Korea.',80000,2),
('Hyundai Accent 2021','Hyundai Accent 2021 facelift launched in November 2020.The Hyundai Accent is a small car (segment B-subcompact car) of the South Korean automaker Hyundai. Hyundais B-class sedan is still assembled domestically and has a very competitive price. In 2020, Accent has sold 20,776 cars, ranking 2nd in the top 15 best-selling cars in Vietnam (only behind rival Toyota Vios - 30,251 cars)',30000,5),
('Hyundai SantaFe','Hyundai SantaFe was first introduced in Vietnam in 2007, after more than 10 years and two generations, the Korean SUV model is trusted by customers thanks to its advantages in design as well as many amenities and handling capabilities. outstanding performance.Currently, the price of Hyundai SantaFe 2021 is  sold in October 2021 with 6 versions.',45000,2),
('Hyundai Kona 2021','Since its launch in the Vietnamese market, Hyundai Kona quickly beat Ecosport to become the best-selling urban small SUV. However, now Kona has had a harder time with the arrival of rookies Kia Seltos and Toyota Corolla Cross. The price of Hyundai Kona car  with 3 versions including standard AT, special AT and Turbo', 30000,2),
('Hyundai Grand i10 2021','Hyundai Grand i10  has continuously been one of the best-selling models of the number one Korean car brand in Vietnam for many years. The A-class car segment is increasingly competitive with a series of notable names such as Kia Morning, Toyota Wigo, VinFast Fadil, Honda Brio, ..Hyundai i10 car price is at 360-455 million VND for 6 different versions of both sedan and hatchback',20000,5),
('Hyundai Elantra 2021','The upgraded version of Hyundai Elantra  was officially introduced in Vietnam in mid-May 2019 with many notable upgrades both inside and out. The new Elantra version  has an appearance designed in the new language "Sensual Sportiness" to bring a strong and sporty feeling.Hyundai Elantra is one of the notable models in the C- segment car segment in Vietnam and competes directly with rivals Mazda 3, Kia Cerato, Toyota Corola Altis...',25000,5),
	--Toyota--
('WIGO 5MT','Get the 5-year/150,000 km warranty right away. The program is valid from June 7 to December 31, 2021. Possessing a sporty appearance with a youthful design language and a wide choice of colors, it deserves to be your first car. Possessing a sporty appearance with a youthful design language and a wide choice of colors, it deserves to be your first car.', 15000,5),
('CAMRY 2.0G','INTELLIGENT DESIGN LANGUAGE RICH. The 2019 Camry version brings a new, extremely eye-catching appearance with a seamlessness in every design detail, which is the focal point to attract eyes when surfing. Spacious, comfortable interior is improved with modern technology, creating a classy and peaceful space. Number of seats: 5 seats. Style: Sedan. 6-speed automatic transmission', 50000,5),
('LAND CRUISER PRADO VX', 'Inheriting the superficial, strong, and solid appearance of the world-famous off-road vehicle; With the design philosophy of "Modern - Smart", Land Cruiser Prado becomes the pride and contributes to enhancing the owner position on all terrains. Spacious space with high-class furniture and modern amenities, combining advanced technology to bring relaxation and great experience, honoring the owner style.', 40000,5),
('VIOS 1.5E MT', 'EMOTIONAL DESIGN. The new VIOS with its emotional design and 5-star safety technology will be an endless source of inspiration for you to explore every road. Experience the sophisticated and luxurious interior space with modern design language. The center console is accented with seamless silver-plated lines in the form of a waterfall flowing from the top. Number of seats: 5 seats. Style: Sedan. Fuel: Gasoline. Origin: Domestic car', 15000,5),
('COROLLA CROSS 1.8V', 'Impressive, dynamic appearance. The design direction of the Corolla Cross is aimed at mature and urban trends, different from current Toyota models. Impressive, dynamic appearance. The design direction of the Corolla Cross is aimed at mature and urban trends, different from current Toyota models. Impressive, dynamic appearance', 10000, 5),
	--Mercedes BenZ--
('Mercedes-AMG', 'Sporty style in luxury sedan design. Welcome to the Mercedes-AMG racetrack. I, the AMG A-Class Sedan, will pave the way to the world of speed and performance. Get in the car, fasten your seat belt, and get ready to experience the ENCOURAGE OF EVERY SECTION! An elegant style in dynamic appearance. Get sporty with the signature grille and AMG spirit-marked equipment. he new generation MBUX (Mercedes-Benz User Experience) infotainment system connects driver and vehicle in a fun way', 70000, 5),
('Mercedes E-Class', 'A more dynamic character all round. Ready to master even the greatest challenge with ease. Discover the outstanding properties of the new E-Class Sedan. As dynamic, elegant and luxurious as never before. The expressive design ensures an agile overall impression. The new E-Class Sedan scores points on several counts: with fine materials and intelligent innovations.', 50000,5),
('Mercedes Maybach S480', 'Mercedes Maybach S480 2021 is a completely new model and has the lowest price of the Maybach S-Class line, so the car has less equipment than other variants but the car design is not much different. The length of the car remains the same, the DxRxC parameters are 5,468x1,920x1,508 mm, and the wheelbase is 3,395 mm.At the front of the car, the Mercedes Maybach S480 has a large grille with chrome plated vertical spokes with the words Maybach on the top of the grille.', 20000,5),
('Mercedes E200 2021', 'The exterior of the new E200 Exclusive has a shift to a more elegant and luxurious style. The car is upgraded and equipped with 7 new points compared to the old E200. That shows that Mercedes has shaped the customer of the E200 as working or middle-aged people. The exterior of the new E200 Exclusive has a shift to a more elegant and luxurious style. The car is upgraded and equipped with 7 new points compared to the old E200.', 17000,5),

--ANTIQUE--
	--Furniture Antiques--
('Antique 1800s rocking chair','An item that has been used previously. The item may have some signs of cosmetic wear, but is fully operational and functions as intended. This item may be a floor model or store return that has been used. See the seller’s listing for full details and description of any imperfections', 200, 3),
('Vintage Wooden Vanity Dresser Table Mirror Swivel Frame Pedestal Victorian','Good vintage pre-owned condition; scratches in wood and flaws in glass. An item that has been used previously. The item may have some signs of cosmetic wear, but is fully operational and functions as intended. An item that has been used previously. The item may have some signs of cosmetic wear, but is fully operational and functions as intended', 1000,3),
('George Nelson Chess Piece Clock', 'Vintage Condition. Style: Mid-Century Modern. Charming middle bed, in the Empire taste, with structure entirely conceived in mahogany veneer.It is built around four detached columns, each surmounted at their ends by a solid mahogany ball. Rich and refined bronzes trimmings, finely chiselled, embellish them in their high and intermediate. Charming middle bed, in the Empire taste, with structure entirely conceived in mahogany veneer.', 6800,3),
('19th Century Empire Style Mahogany Bed','Vintage Design.Charming middle bed, in the Empire taste, with structure entirely conceived in mahogany veneer. It is built around four detached columns, each surmounted at their ends by a solid mahogany ball. Rich and refined bronzes trimmings, finely chiselled, embellish them in their high and intermediate',3600,3),
('Antique Estonian Dining Chairs from Luterma, 1910s','Set of 6 former pub chairs / bistro chairs from the Art Nouveau period around 1910. Particularly beautiful are the embossed seats, which together with their elegant swing make the chairs a real eye-catcher.Light wear consistent with age and use, Patina consistent with age and use, Partially restored, Surface has been polished, Surface has been refinished, Restored', 4000,3),
('Antique Writing Desk, 1700s', 'Louis XVI writing desk in inlaid walnut wood with front drawer. Good — This vintage item remains fully functional, but it shows sign of age through scuffs, dings, faded finishes, minimal upholstery defects, or visible repairs. Good — This vintage item remains fully functional, but it shows sign of age through scuffs, dings, faded finishes, minimal upholstery defects, or visible repairs.', 5000, 3),
	--Ancient Pottery--
('Euphronios Sarpedon krater God Hermes Vase Ancient Greek Pottery Ceramic Copy','New: A brand-new, unused, unopened, undamaged item in its original packaging (where packaging is applicable). Packaging should be the same as what is found in a retail store, unless the item is handmade or was packaged by the manufacturer in non-retail packaging, such as an unprinted box or plastic bag.', 4700,3),
('Geometric Krater 16cm,Ancient Greek Pottery Vase','A brand-new, unused, unopened, undamaged item in its original packaging (where packaging is applicable). Packaging should be the same as what is found in a retail store, unless the item is handmade or was packaged by the manufacturer in non-retail packaging, such as an unprinted box or plastic bag.', 8000,3),
('Minoan Vase Ceramic Pottery Painting Octopus Ancient Greek Crete Knossos',' A brand-new, unused, unopened, undamaged item in its original packaging (where packaging is applicable). Packaging should be the same as what is found in a retail store, unless the item is handmade or was packaged by the manufacturer in non-retail packaging, such as an unprinted box or plastic bag',3000,3),
('Dionysus Satyr Death of Orpheus Krater Vase Ancient Greek Pottery Museum Copy','Handmade:	Yes. Time Period Manufactured:	2020-NowSize:	Large	Country/Region of Manufacture:	Greece. Material:Ceramic, Clay	Featured Refinements:	Greek VaseBrand:	Handmade	Color:	MulticolorTheme:	Greek	Item Model Number:	K32Type:	Vase', 2000,3),
('Dionysus Satyr Death of Orpheus Krater Vase Ancient Greek Pottery Museum Copy','Handmade:	Yes. Time Period Manufactured:	2020-NowSize:	Large	Country/Region of Manufacture:	Greece. Material:Ceramic, Clay	Featured Refinements:	Greek VaseBrand:	Handmade	Color:	MulticolorTheme:	Greek	Item Model Number:	K32Type:	Vase', 2000,3),
	--Ancient Clock--
('STAR WORK Glass 30 cm Battery Operated Non-Ticking Silent Classic Quartz Easy to Read Wall Clock','Non-Ticking Silent Wall Clock: A silent quartz sweep continuous-movement clock motor ensures accurate time keeping and absolutely quiet working or sleeping environment. Wall clocks are perfect for adding artful appeal to your wall. Perfect for bedroom,school,office,living room,kitchen or commercial applications.Classic clock is a perfect gift for housewarmings, Christmas, birthdays, weddings or any special occasion.', 5000,3),
('Amazon Brand - Solimo 12-inch Wall Clock - Classic Roulette','Dial size: 12 inches in diameterMaterial of the frame: Plastic. Material of the transparent face: GlassBig, clear representation of the numbers on the clockMakes no sound while tracking time, sweep movement. Ideal for living room, bedroom & offices. Pack contents: 1 Wall Clock, 1 AA battery. Ebros Ancient Egyptian Bastet Table Clock Statue 6.75" Long with Roman Numerals',2000,3),
('Egyptian Winged Isis Clock, Fine Ancient Egyptian Statues','Egyptian Winged Isis Clock Figurine :   Beautiful Hand-made and Painted Figurine of Winged Isis with Quartz Alarm Clock (1 AA Battery Included). Product Details. Title: "Egyptian Winged Isis Clock Figurine".Size: 5" Wide, 4" Tall, 1.35" DeeoWeight: 7 Oz.Origin: Hand Made and Painted in Egypt (Year: 2005). Condition: Brand New Item, Hand-Painted Risen in Mint Condition. Comes in the Original box shown and packaging.', 3000,3),
('Vintage Farmhouse Kitchen Wall Clocks','This is a retro styled analog wall clock made from wood. This clock will add charm to any room in your home. There is a plastic shell casing behind the clock for batteries. Only one AA battery is required for this clock ( not included ). This vintage wall clock can be a good gift at housewarmings, weddings, and social gatherings.',1500,3),
('New Vintage Wooden Table Clock Bedroom','Bedside Snooze Alarm Clock wood Retro Desktop Clocks Home Decoration Desk Table Watch. New Vintage Wooden Table Clock Bedroom Bedside Snooze Alarm Clock wood Retro Desktop Clocks Home Decoration Desk Table Watch. Name: Wooden Alarm Clock. Style: European, American, casual. Appearance: Tower shape. Dial material: metal. Clock color: wine red. Applicable places: living room, bedroom, study room, office, kitchen', 1900, 3),
	--Ancient Weapons--
('European Swords & Daggers, Pre-1700 - ENGLISH HUNTING HANGER, 2ND HALF 17TH C', 'Featuring iron hilt with down-turned pierced shell guard on the obverse, single reversescroll quillon, and knucklebow attaching through a small hole in the capstan pommel with button; remains ofengraved decoration on pommel. Tapering cylindrical one-piece horn grip with iron base ferrule. Curved 23″ single-edged blade with broad full-length fuller (point slightly rounded). Blade engraved on the upper half with scrolling floral decoration.', 1100,3),
('ENGLISH PLUG BAYONET BY JOHN HATHAWAY, CA. 1690','Featuring tapering 11 ½” single-edged wedge-section blade, double-edged for the last 51/4″. The forte is deeply stamped on one side with the Blazing Star mark assigned to John Hathaway by the Worshipful Company of Cutlers of London on September 26, 1689 and also an unidentified King’s Head mark (KH18 in R.D.C. Evans’ “The Plug Bayonet”). While the King’s Head was a mark used by Solingen makers Weyersberg and Wundes',2000,3),
('FRENCH AND INDIAN WARS ERA SPIKED TOMAHAWK','Classic fighting spike ax of the Iroquois Federation. Original untouched example featuring a 10 inch hand-forged head with elliptical eye; original handle showing incised lines and inactive worm holes. This French and Indian Wars era tomahawk was from the famous Robert Wheeler Collection.  Mr. Wheeler was a renowned author and expert on Revolutionary War weaponry', 2000,3),
('GOLD HANDLED CIVIL WAR PRESENTATION CANE OF COLONEL WOUNDED IN ACTION','Presentation cane with hardwood shaft surmounted by a hallmarked gold cap inscribed in script: “Presented /To/Col. J.W. Jenkens/by 31st Iowa/Infty.” Overall length 32 ½”. The cane has a modern rubber tip, mild marks and scratches along the shaft, and some dents and light scratches on the gold handle. He died in Kansas City on June 24th, 1903, reportedly hastened by injuries sustained when struck with a club during a robbery.', 900, 3),
	--Ancient Books--
('1845 Rare Book bound by the Monastery Hill bindery - REYNARD THE FOX. Medieval Fables.', 'Attractive, rare and beautiful edition of REYNARD THE FOX. A renowned Apologue of the Middle Age, reproduced in Rhyme... Reynard the Fox is a literary cycle of medieval allegorical Dutch, English, French and German fables. The first extant versions of the cycle date from the second half of the 12th century. The genre is very popular throughout the Late Middle Ages, and in chapbook form throughout the Early Modern period.', 3500,3),
('1869 Rare Victorian Book - DAVID COPPERFIELD by Charles Dickens Illustrated by Browne.','A nice early edition of David Copperfield. Published by Chapman and Hall (193, Piccadilly). The Personal History of David Copperfield is a novel in the bildungsroman genre by Charles Dickens, narrated by the eponymous David Copperfield, detailing his adventures in his journey from infancy to maturity. It was first published as a serial in 1849–50, and as a book in 1850.',1300,3),
('1870 Rare Book - The LAMPLIGHTER by Maria Susanna Cummins.','Rare and nice early edition of The Lamplighter -- a sentimental novel written by Maria Susanna Cummins and published in 1854, and a best-selling novel of its era. The Lamplighter tells the story of Gertrude Flint, an abandoned and mistreated orphan rescued at the age of eight by Trueman Flint, a lamplighter, from her abusive guardian, Nan Grant. Gertrude is lovingly raised and taught virtues and religious faith. She becomes a moralistic woman.', 900,3),
('1885 First Edition - CONJURER Dick or, The Adventures of a Young WIZARD by Professor Hoffmann.','Scarce and attractive First edition of Conjuror Dick; or, The adventures of a young wizard -- a fictional book by Angelo John Lewis (Professor Hoffmann) published in 1885. It tells the fictional life story of a boy magician name Dick Hazard and his travels and adventures, in the company of a professional exhibitor as his assistant"', 3500, 3),
('1900 Rare PALMISTRY Book - CHEIRO LANGUAGE OF THE HAND with reproductions of Famous Hands.','Attractive and rare edition of Cheiro Language of the Hand. Cheiro had a wide following of famous European and American clients during the late 19th and early 20th centuries. He read palms and told the fortunes of famous celebrities like Mark Twain, W. T. Stead, Sarah Bernhardt, Mata Hari, Oscar Wilde, Grover Cleveland, Thomas Edison, the Prince of Wales, General Kitchener, William Ewart Gladstone, and Joseph Chamberlain.', 1400,3),

--FASHION--
	--Bracelet--
('Medical Alert Bracelet','A stunning medical alert bracelet with the medical symbol in black. Choose from 18 or 21cm in length with complimentary laser engraving in an easy to read font. I am hypoallergenic, non-tarnishing surgical stainless steel. A sturdy, allergy-free, waterproof metal that is corrosion-free and incredibly durable, making me perfect for everyday wear. I am easy to maintain; we have put together this easy to follow cleaning guide for you.', 550,4),
('Cherish Cuff Bracelet: I can and I will','Approx Length: 16cm adjustable cuff bracelet; this will fit most wrist sizes, children to men and women. Our cuff bracelets are made from a sturdy, anti-tarnishing, allergy-free and waterproof metal that is perfect for everyday wear. I am easy to maintain; we have put together this easy to follow cleaning guide for you. By clicking this link, you will be able to see how easy our pieces are to clean.', 220, 4),
('Jessica Bangle','The Jessica bangle fits from approximately 55mm to a 70mm size wrist, with a simple squeeze of the bangle. The Jessica bangle has a classic 10mm knot. A 5mm solid ball is highlighted on the end of each side to finish off this gorgeous style that is our Jessica bangle. I am hypoallergenic, non-tarnishing surgical stainless steel. A sturdy, allergy-free, waterproof metal that is corrosion-free and incredibly durable, making me perfect for everyday wear', 220,4),
('Medical Alert Bracelet','A stunni ng medical alert bracelet with the medical symbol in black. Choose from 18 or 21cm in length with complimentary laser engraving in an easy to read font.I am hypoallergenic, non-tarnishing surgical stainless steel. A sturdy, allergy-free, waterproof metal that is corrosion-free and incredibly durable, making me perfect for everyday wear. I am easy to maintain; we have put together this easy to follow cleaning guide for you.',550,4),
('Medical Alert Bracelet','A stunning medical alert bracelet with the medical symbol in black. Choose from 18 or 21cm in length with complimentary laser engraving in an easy to read font. I am hypoallergenic, non-tarnishing surgical stainless steel. A sturdy, allergy-free, waterproof metal that is corrosion-free and incredibly durable, making me perfect for everyday wear. I am easy to maintain; we have put together this easy to follow cleaning guide for you.', 800,4),
	--Necklace--
('Pave Butterfly Initial Choker','Gold vermeil choker. Lobster clasp closure. Butterfly and initial charms. Cubic zirconia accents. Measures approx 30 cm in length with a 8 cm extender. Gold vermeil choker. Lobster clasp closure. Butterfly and initial charms. Cubic zirconia accents. Measures approx 30 cm in length with a 8 cm extender. 14k gold plated necklace. Lobster clasp closure. Curb chain. Swarovski pearl accents. Measures approx 38 cm in length with a 5 cm chain extender.', 200,4),
('18kt yellow gold Teeny Tiny Rabbit pendant necklace', '18kt yellow gold Teeny Tiny Rabbit pendant necklace. Hop into the new season. And by that we mean in this 18kt yellow gold Teeny Tiny Rabbit pendant necklace from Alex Monroe. How adorable. Let us handle the legwork. Delivery duties are included in the item price when shipping to all EU countries plus The United Kingdom, USA, Canada, China Mainland, Australia, New Zealand, Puerto Rico, Switzerland, Singapore, Republic Of Korea, Kuwait, Mexico, Qatar, India.', 600,4),
('Best Yet To Come heart pendant necklace','Brinker & Eliza-Best Yet To Come heart pendant necklace. Brinker & Eliza necklace is a reassuring reminder that The Best Is Yet To Come. Cast from gold-tone brass chain links, its punctuated with a heart-shaped pendant thats oh-so-romantic. Treat yourself. The model is also styled with: GANNI high-rise wide-leg trousers, GANNI wrap-detail blazer jacket, Jil Sander ball accent thong sandals, REMAIN Gere ribbed-knit vest top.',100,4),
('Gucci-GG sterling silver necklace','GG sterling silver necklace-Calling all Gucci aficionados. This sterling silver necklace has a burnished antique effect that makes it look as though its been passed down for generations. Its made to be treasured. Highlights sterling silver , lobster claw fastening, logo pendant, antique effect. Made in Italy. This sterling silver necklace has a burnished antique effect that makes it look as though its been passed down for generations. Its made to be treasured.',200,4),
('Saint Laurent-Curb chain necklace','Your look could be off-the chain. All you need is this silver-tone metal curb chain necklace from Saint Laurent. It features an embossed logo and a clasp fastening. And a serious dose of cool. Made in Italy. Your look could be off-the chain. All you need is this silver-tone metal curb chain necklace from Saint Laurent. It features an embossed logo and a clasp fastening. And a serious dose of cool.', 600,4),
('Versace-Greca Medusa detail necklace','In dire need of causing a serious visual impression? The moment you decided to throw on this gold-tone Greca Medusa detail necklace from Versace thats precisely what you did. Evidently so. Highlights gold-tone, brass, signature Greca detailing. Medusa head motif, lobster claw fastening, polished finish. Made in Italy', 400,4),
	--Fashion Shoes--
('Dolce & Gabbana-City leopard-print ankle boots','Dolce & Gabbana takes inspiration from snowy-day style to deliver these ankle boots. Boasting a padded construction, the pair is adorned with an all-over leopard print in line with the brand penchant for bold designs. The model is also styled with: Dolce & Gabbana large quilted Devotion shoulder bag, Wolford x Amina Muaddi sleeveless catsuit, Aleksandre Akhalkatsishvili faux-leather belted padded coat.',800,4),
('Balmain B-Bold high-top sneakers','Balmain signature opulent style is celebrated in this version of the B-Bold sneakers. The high-top silhouette is updated with an embossed crocodile effect and two logo-embossed straps at the upper. Highlights: black,calf leather,round toe,embossed crocodile effect,sock-style ankle,logo-embossed straps,front touch-strap fastening,ankle-length,pull-tab at the heel,platform sole', 900,4),
('Alexander McQueen Kids Oversized low-top sneakers','Alexander McQueen extends its signature Oversized shoe silhouette to its kidswear line with this all-black iteration. Crafted from patent leather and boasting a high-shine finish, these sneakers lace up at the front and sit atop a familiar chunky rubber sole for a voluminous design. Highlights: black,leather,high-shine finish,chunky rubber sole,front lace-up fastening,round toe,branded heel counter. Made in Italy',500,4),
('Nike Kids Air Max 720 sneakers','Supplied by a premier sneaker marketplace dealing with unworn, already sold out, in demand rarities. Each product is rigorously inspected by experienced experts guaranteeing authenticity. The best part of childhood is being able to jump about, do whatever you please and have fun. Which makes these black Air Max 720 sneakers from Nike the perfect pick for providing a comfortable low-top silhouette to any event. Adventure awaits.',100,4),
('MACH & MACH Diamond of Elizabeth transparent pumps','Georgian footwear brand Mach & Mach creates eye-catching silhouettes for statement looks. Crafted in a transparent black shade, the Diamond of Elizabeth pumps are adorned with glistening crystals over their pointed toes and boast a pearl chain that wraps around the ankle.', 100,4),
('JW Anderson Chain loafer mules','First seen in the AW20 runway show, these loafers from JW Anderson combine both style and comfort. Crafted from white leather, the slip-on pair is accented with a chunky chain-link detail in a polished tonal design. Highlights: white,leather,chain-link detailing,round toe,slip-on style,branded insole,cork sole,flat rubber sole',500,4),
	--Dress--
('Jacquemus-Valdu sleeveless maxi dress','With a cut out back and tonal strap detailing, the Valdu dress embodies two key features of Jacquemus visual identity. Presented in classic beige, the piece is discreetly punctuated by gold-tone hardware. The model is 1.76 m wearing size 36 (FR). The model is also styled with: BY FAR Fida 100mm leather sandals, Jacquemus Le Chiquito Moyen mini bag. Washing instructions: Dry Clean Only',900,4),
('Fendi-FF Karligraphy satin dress','This slip dress from Fendi is crafted from satin whose lustrous finish is highlighted by a fluid two-layer design. It is finished with FF Karligraphy openwork embroidery that showcases the Italian powerhouse rich history. Outer: Silk 100%, Viscose 100%. The model is 1.77 m wearing size 40', 200,4),
('GANNI - Leather mini shirtdress','GANNI transforms the traditional shirtdress by crafting it using leather. The white contrast stitching adds a contemporary appeal, while the self-tie belt cinches the waist of the brand signature boxy shape, conveyed through the short sleeves. POSITIVELY CONSCIOUS: This brand measures the impact of every item they produce and supplies a Carbon Neutral Certification with each purchase, which measures the environmental impact of production and shows that they have covered the cost of making the carbon footprint neutral.',600,4),
('Cecilie Bahnsen-Holly off-shoulder midi dress','Known for adding a twist to Scandinavian minimalism, Cecile Bahnsen plays with details and proportions. Crafted from recycled materials in a versatile light-grey hue, the Holly dress is a prime example. It is cut to an empire line silhouette with an ankle-grazing flared skirt, framed by thin spaghetti straps and long puff sleeves that drape from below the shoulder, enhancing the voluminous shape.', 900,4),
('There Was One-Mid-length spaghetti-strap slip dress','Crafted in a black satin weave, this dress from There Was One was designed to transcend the seasons. Finished with a square neck and spaghetti straps, the mid-length silhouette is both elegant and timeless. This garment contains materials certified by the Forest Stewardship Council (FSC), which ensure that the wood used comes from responsibly managed forests.', 400,4),
('Versace Greca logo-print minidress','Highlights: deep-orange/royal-blue, wool-silk blend,signature Greca-pattern print,round neck,short sleeves,fitted waistline. Made in Italy. The model is 1.78 m wearing size 40 (IT). The model is also styled with: Off-White Arrows pendant earrings, Balmain B-Buzz baguette bag, Jil Sander square-toe 95mm knee-high boots.', 400,4),
	--Jacket--
('Moncler-Avoine cropped padded jacket','Known for their padded down jackets, Italian fashion house Moncler was founded in 1952 and started life creating quilted sleeping bags and tents. Presented in a grey hue, this Avoine cropped jacket is detailed with the label signature logo patch to the outer left sleeve. The model is also styled with: Totême square-toe Chelsea boots, Saint Laurent diamond-quilted scarf, OpéraSPORT Claude logo print T-shirt.',500,4),
('Frankie Shop - Olympia oversized single-breasted blazer','We might have just found your dream jacket. Made from faux leather and cut for an oversized fit, this Olympia blazer buttons up at the front with a single-breasted design and boasts notch lapels for a sleek yet relaxed look. Outerwear perfection. The model is also styled with: Frankie Shop Manon high-waisted shorts, Lemaire open-toe flat mules, LVIR contrast-stitch long-sleeve shirt, Jil Sander drawstring leather mini bag.', 400,4),
('Fendi Scribble-detail logo down jacket','Scribble-detail logo down jacket - Highlights: black,down-feather filling,logo print to the front,logo print to the rear,abstract pattern print,high neck,front zip fastening,long sleeves. Made in Italy. Outer: Polyester 100%. Lining: Polyester 100%, Polyamide 100%, Down 75%, Feather 25%. The model is 1.85 m wearing size L', 600,4),
('New Season Jacquemus - Zipped shirt jacket','Highlights: black, cotton-virgin wool blend ,classic collar, front zip fastening, long sleeves, buttoned cuffs, two button-fastening chest pockets, curved hem. Composition: Outer: Virgin Wool 80%, Polyamide 20%. Lining: Cotton 55%, Polyester 45%. The model is also styled with: 1017 ALYX 9SM two-tone chain-link necklace, Jacquemus La Chemise floral-print shirt, Bottega Veneta Eyewear geometric oversized-frame sunglasses, Bonastre Bon Bon leather shoulder bag, A-COLD-WALL* x Dr.',700,4),
('Moncler Enfant - Ercan printed-logo down jacket','Designed in an off-white hue, this Ercan jacket from Moncler has been constructed with a feather down interior. Boasting an oversized logo print to the rear, it features two side zip-fastening pockets and a contrasting logo patch to the chest.Composition: Outer: Polyamide 100%. Lining: Feather Down 100%, Polyamide 100%',600,4),
('Moncler Enfant - New Maya puffer jacket','Moncler Enfant New Maya puffer jacket provides comfort in cold weather thanks to its padded design and a hood too. The model is 1.07 m wearing size 10 (yrs). The model is also styled with: Bonpoint double-breasted hooded trench coat, Moncler Enfant logo-print cotton sweatshirt, Moncler Enfant logo-patch pompom beanie, MM6 MAISON MARGIELA KIDS loose-fit jeans, UGG Kids fluffy yeah slides.',600,4),
	--Jeans--
('AMBUSH-REGULAR FIT DENIM PANTS BLU WASHED NO CO','Composition: Cotton 100%, Leather 100%. Composition: Cotton 100%, Leather 100%. The model is 1.86 m wearing size 32 (Waist). The model is also styled with: AMBUSH turtleneck jersey T-shirt, Eytys Luciano Western-style boots, Givenchy Antigona U camera bag, Emanuele Bicocchi Stone signet ring, Wacko Maria leopard knit cardigan.',200,4),
('ERL Cropped straight-leg jeans','Highlights: washed blue, cottons, tone washed, whiskering effect at the thighs, belt loops, front button fastening, straight leg. Made in Italy. The model is 1.78 m wearing size M. The model is also styled with: Tibi turtleneck wool knit top, Karen Wazen Kaia oversized-frame sunglasses, ERL faux-fur single-breasted jacket, Yuzefi Bom tote bag, Off-White arrow earrings.',200,4),
('Ralph Lauren Kids Eldridge skinny-fit jeans','Polo Ralph Lauren is the master of all things smart-meets-casual. These Elridge jeans are the prime example, thanks to their comfortable stretch cotton blend and skinny-fit design. Composition: Cotton 92%, Elastane 8%. Washing instructions. Machine Wash', 100,4),
('Maison Margiela-Distressed straight-leg jeans','Maison Margiela may look relatively tame but they are anything but basic. A little baggy, they have a straight-leg shape and are slashed at the sides to reveal a little skin. Oo er. Featuring a button and zip fly, belt loops, a five pocket design, a distressed detail and a high rise.', 400,4),
('Valentino x Levi’s bootcut high-rise jeans','Combining denim excellence with Italian luxury, these Valentino x Levi’s high-rise jeans embody the best of the two brands. Designed with a flattering bootcut, the pair stands out in this collaboration. The model is 1.78 m wearing size 28 (in). The model is also styled with: Alexander McQueen oversized sole sneakers, Bottega Veneta The Triangle tonal-design tote bag.',500,4),
	--Watch--
('MAD Paris x 1017 ALYX 9SM pre-owned customised Royal Oak','Fine watch specialist MAD Paris presents a new take on a classic. The customised professionals have partnered up with Matthew M. Williams, the creative force behind 1017 ALYX 9SM, to welcome this Audemars Piguet Royal Oak to the latest collection. Crafted from 18kt gold, the sleek piece combines both a timeless model with a contemporary finish the label is known for.',100,4),
('Rolex 2021 unworn Cosmograph Daytona 40mm','Swiss luxury timepiece specialist Rolex is known for presenting sports-influenced designs that will withstand the test of time. A nod to the car racing that took place every year on Daytona Beach, this 2021 unworn Cosmograph Daytona 40mm model was born out of the love of all things motor, complete with a tachymeter scale on the outer ring and a telemeter on the inner as a tribute to the fast life of watches and cars. ',100,4),
('Briston Watches Streamliner Ad-Venture 44mm','French watchmakers Briston were born out of a rich inspiration from British sports. Unique in style with a contemporary finish, the Streamliner Ad-Venture 44mm is finished with a digital dial to offer both a sleek yet retro-inspired design for modern wear.',300,4),
('Zadig&Voltaire Montre Butterfly 40mm watch','Silver-tone stainless steel and glass Montre Butterfly 40mm watch from Zadig & Voltaire featuring micro stud details, a butterfly print and an adjustable fit. Composition: Stainless Steel, Glass',200,4),
('Tommy Hilfiger Contrast bezel quartz 38mm','Tommy Hilfiger has been the leading brand when it comes to American heritage with an effortless air. Since 1985, each collection presents an opportunity to welcome timeless and classic designs, like this contrast bezel quartz 38mm that features a multifunction dial for appeal.', 150,4),

--ELECTRONICS--
	--Phone--
('360° Car Air Vent Phone Holder', 'Holder base rotates 360° for omnidirectional functionality- Holds smartphone devices in place.- Helps provide convenience when it comes to using electronic devices while driving. Provides additional safety while driving and easily attaches onto car consoles. Suitable for phones with screen sizes between 4 - 6 inches. Modern design complemented by sturdy grip that prevents slippage. Made from lightweight and durable material. Quantity : 1 piece. Size : 6.5 x 5.3 x 11 cm.', 30,5),
('Apple AirPods (2nd Generation)','About this item: Automatically on, automatically connected. Easy setup for all your Apple devices. Quick access to Siri by saying “Hey Siri”. Double-tap to play or skip forward', 100,5),
('Ailun Glass Screen Protector Compatible for iPhone 11/iPhone XR, 6.1 Inch 3 Pack Tempered Glass','About this item: WORKS FOR iPhone 11/iPhone XR (2019/2018 release) 6.1 Inch display ,0.33mm tempered glass screen protector. Featuring maximum protection from scratches, scrapes, and bumps.. Specialty: Due to the rounded design of the iPhone 11/XR and to enhance compatibility with most cases, the Tempered glass does not cover the entire screen. HD ultra-clear 99.99% touch-screen accurate.',50,5),
('iPhone Charger','About this item: DURABLE MATERIAL: Phone cable With 8000+times bend lifespan and integrated molding process, the nylon braided jacket is super smooth and comfortable,more durable than standard Phone charger cord. PERFECT LENGTHS: Perfect 6feet extra long phone charger cable free up your charging time, no more being stuck to wall socket, ideal for using at home, in car and office.',20,5),
('Xperia PRO Portable High Speed Transmission Device & Smartphone with HDMI Input, 6.5" 4K HDR OLED Screen, 5G mmWave','About this item. World’s first smartphone w/ HDMI connectivity to capable cameras. Fast reliable signal w/ unique 360-degree 4-way 5G mmWave antenna. 6.5” 4K HDR 21:9 OLED display doubles as camera monitor via HDMI. Livestream w/ services like YouTube using HDMI connected camera. Fast, easy file transfer w/ USB-C and FTP upload via 5G connectivity',600,5),
	--Computer--
('Lenovo IdeaPad', '1 14 14.0" Laptop, 14.0" HD (1366 x 768) Display, Intel Celeron N4020 Processor, 4GB DDR4 RAM, 64 GB SSD Storage, Intel UHD Graphics 600, Win 10 in S Mode, 81VU0079US, Ice Blue. This everyday laptop is powered by an Intel Celeron N4020 processor, 4GB DDR4 RAM, and 64 GB M.2 PCIe SSD storage. This everyday laptop is powered by an Intel Celeron N4020 processor, 4GB DDR4 RAM, and 64 GB M.2 PCIe SSD storage', 300,5),
('Seagate Portable 2TB External Hard Drive Portable HDD – USB 3.0 for PC, Mac, PS4, & Xbox - 1-Year Rescue Service','Easily store and access 2TB to content on the go with the Seagate Portable Drive, a USB external hard drive. Designed to work with Windows or Mac computers, this external hard drive makes backup a snap just drag and drop. To get set up, connect the portable hard drive to a computer for automatic recognition no software required',50,5),
('Logitech BRIO Ultra HD Webcam for Video Conferencing, Recording, and Streaming - Black','Spectacular video quality: A premium glass lens, 4k image sensor, high dynamic range (Hdr), and autofocus deliver beautiful, true to life video.Look great in any light: Right light 3 automatically adjusts exposure and contrast to compensate for glare and backlighting. Supports multiple connection types, including USB 2.0 type a and USB 3.0 type a and C connections.', 200,5),
('BENGOO G9000 Stereo Gaming Headset',' For PS4 PC Xbox One PS5 Controller, Noise Cancelling Over Ear Headphones with Mic, LED Light, Bass Surround, Soft Memory Earmuffs for Laptop Mac Nintendo NES Games. 【Multi-Platform Compatible】Support PlayStation 4, New Xbox One, PC, Nintendo 3DS, Laptop, PSP, Tablet, iPad, Computer, Mobile Phone. Please note you need an extra Microsoft Adapter (Not Included) when connect with an old version Xbox One controller.',30,5),
	--Electronice device--
('Electric Chopper','Four S-shaped blades allow for omnidirectional slicing and dicing for quick and evenly processed food. It can also be used with beans, nuts, and other foods that wish to process. Simple one-touch operation. Powerful and silent motor helps save time when it comes to ingredient preparation. The grinder body is made of food-grade plastic that is easy-to-clean and easy-to-store. Suitable for usage in residential areas, kitchens and anywhere else as needed.',30,5),
('CCTV Camera','1080P HD indoor, plug-in security camera with motion detection and two way audio that lets you monitor the inside of your home day and night. Get alerts on your smartphone whenever motion is detected or customize motion detection zones so you can see what matters most. Store events conveniently and securely in the cloud with a 30-day free trial of the Blink Subscription Plan or locally with the Sync Module 2 and a USB flash drive (USB sold separately).',60,5),
('GreaterGoods Digital Food Kitchen Scale, Multifunction Scale Measures in Grams and Ounces','A Premium Choice: Between the design and quality, this kitchen scale is going to last and function at an impeccable level. Your cooking just got ten times easier. Fresh Features: All of the qualities you need and expect in a kitchen scale: readings down to the gram, an eleven pound capacity, and easy to read display. What more could you want?. ', 15,5),
('Power Blender & Processor','The 3-in-1 blender that crushes, food processes, and makes dough. Smart TORQUE is designed to power through heavy loads without stalling or the need to stir or shake. Variable speed control. Start slow and ramp up as needed for precision chopping and mixing. Power Blender & Processor Pitcher: crush, chop, and make dough conveniently in one pitcher.', 100,5),
('Heater','2 in 1 heater fan: This ceramic heater provides two heat levels, 1500W or 750W and one cool air fan, you can use it both for winter and summer. Thermostat control of the heater will turn the heater off when it reaches a preset temperature and turn the heater back on when the temperature dips below the thermostat setting. It will cycle on and off. Adjust the setting of thermostat from 0℉ to 158℉ to keep room comfortable', 45,5),
('Honeywell HT-900 TurboForce Air Circulator Fan Black, Small','Small fan for table or floor: The Honeywell turbo force air circulator fan has 3 speeds & a 90 degree pivoting head. This quiet fan is compact enough for on a table or wall mount & powerful enough to help provide comfortable cooling in small-medium rooms.', 15,5),

--COLLECTION--
	--Wine--
('Apothic Red Blend Winemaker Blend Wine 2019 - 750 ML','A masterful red blend wine featuring rich Zinfandel, smooth Merlot, flavorful Syrah, and bold Cabernet Sauvignon. These unique elements come together to create a red blend with layers of dark red fruit complemented by hints of vanilla and mocha.',10,6),
('Juggernaut Hillside Cabernet Sauvignon 2019 - 750 ML','French oak beautifully transforms intense mountain fruit into a wine with uncommon richness, yet smooth and luxurious texture. Juggernaut Hillside Cabernet is a wine that is fierce, brave, and delicious. Rich and intense with a complex character and smooth finish. Luxurious texture with black currants and vanilla. Aroma of licorice and blackberry.',15,6),
('Bogle Vineyards Cabernet Sauvignon 2018 - 750 ML','This complex and developed fruit is showcased in the glass with first impressions of dried cherries, tobacco leaf and Madagascar vanilla. Wrapping the palate in richness, the full bodied flavors of cherry and plum compote resonate, followed by touches of tanned leather and dark chocolate. Aging in one-year old American oak for 12 months creates a finish with ample and enduring tannins, and tones of sweet tobacco smoke and spicy oak.',20,6), 
('Decoy Sonoma Cabernet Sauvignon 2019 - 750 ML','Displaying the lushness and balance that define great Sonoma County Cabernet Sauvignon, this inviting wine features layers of blackberry and black cherry, alongwith notes of mocha, star anise and spearmint. On the palate, the juicy, bright fruitflavors are framed by rich, refined tannins that carry the wine to a satisfying finish. Blend: 88% Cabernet Sauvignon, 8% Merlot, 2% Petite Verdot, 1% Petit Sirah, 1% Cabernet France', 15, 6),
('Orin Swift Cellars Abstract Wine 2019 - 750 ML','As soon as a glass is poured, aromatic notes of Luxardo cherries, ripe black plums and raspberries billow, with intricate hints of coffee, mocha and caramel in the background. The entry is expansive with dark briar fruits, cola and cocoa with tannins that are soft and dusty. The wine finishes with a hint of wild cherry and a lingering sweet oak presence.',30,6),
	--Stamp--
('American Coin Treasures 40 U.S. Postage Stamps from The 1910s, 1920s, 1930s and 1940s','Stamps from 4 decades: Mint US Postage Stamps. All stamps guaranteed to be over 65 years old. Comes wrapped in plastic with cardboard protector. Includes A Certificate of Authenticity, 1 Year Manufacturers Warranty.',10,6),
('Military Working Dogs U.S. Postage Stamps Sheet of 20 Forever Postage Stamps Scott 4508B','Available at a lower price from other sellers that may not offer free Prime shipping. These new red, white and blue forever postage stamps featuring military working dogs are designed to honor the nation’s brave and loyal canines. The sheet of 20 stamps features artist renderings of four breeds commonly used as military working dogs: German shepherd, Dutch shepherd, Labrador retriever and Belgian Malinois',18,6),
('Christmas Carols - USPS Forever Stamps Book of 20 - New 2017 Release','Forever stamps are always equal to the USPS first-class one ounce letter rate. Double-sided booklet of 20 Forever stamps. Perfect for holiday mailings, gifts & more. Images from popular holiday songs. Great for christmas cards, holiday cards, and more', 15,6),
('2018 Madonna and Child by Bachiacca Forever Postage Stamps','This "Madonna and Child by Bachiacca" forever postage stamp was released in October 2018. This forever postage stamp features a detail of Bachiacca’s oil-and-gold-on-panel painting “Madonna and Child,” which dates from the early 1520s, showing the Christ child clutching a bouquet of jasmine, a symbol of divine love, alongside the Virgin Mary’s profile, left shoulder and right hand.',25,6),
('Celebration Boutonniere USPS Forever Stamps Sheet of 20 - New Stamp Issued 2017','This beautiful stamp can be used on RSVP envelopes often enclosed with wedding invitations, party invitations, thank-you notes, announcements, or any other correspondence. Celebration Boutonniere is similar in design to the Celebration Corsage Forever stamp, and the two form a natural pair.', 25,6),
	--Coin--
('2021 American Silver Eagle 1 oz Type 2 Coin In U.S. Mint Box $1 Brilliant Uncirculated US Mint','2021 AMERICAN SILVER EAGLE $1 TYPE 2 (NO MINT MARK). U.S MINT BOX (no COA). BU (Brilliant Uncirculated). - NOT A PROOF OR BURNISHED EAGLE. Great addition to any collection,Great gift for all encapsulated in air tite capsule to preserve the coin.', 45,6),
('U.S. Liberty Head (Barber) Nickels - 7 Coin Grab Bag', 'U.S. Liberty Head (Barber) Nickels. Composition: Copper Nickel; Diameter: 21mm. Most coins in the U.S. Liberty Head (Barber) Nickels grab bags are dated between 1899 and 1912. Coins all have readable dates and range from AG (Almost Good) to VG (Very Good). Perfect for gift giving',10,6),
('John Wick Prop Continental Hotel Collection Gold Coin','MATERIAL: Zinc Alloy, High Precision Manufacturing, Plating Procedures. CHARACTER: Thriller Movie John Wick Copslay Acccessory. SIZE: Coin Size: 1.5" in Diameter and 0.118" Thick; ONE PICE WEIGHT: 1.06oz; PACKAGE INCLUDES: 1*PC. DESIGN: 1, Obverse: Features a Lion in Stride with a Large Shield in the Background. "Ens Causa Sui" and “MMI” can be Read Along the Top and Bottom; 2"',10,6),
('CA 2021 Lot of (10) 1 oz Silver Canadian Maple Leaf Coins Brilliant Uncirculated with our Certificates of Authenticity by CoinFolio BU','Purity: .9999 Fine Silver. Diameter: 38 mm; Thickness: 3.29 mm. Metal Content: 1 Troy Ounce per Coin; Total: 10 Troy Ounces. You will receive ten coins per purchase inside the original Royal Canadian Mint acrylic tube. Stock Photo; Image is indicative of quality; Coins will come with ten certificates of authenticity', 100,6),
('10,000 Amazon Coins','Buy Amazon Coins and save on apps, games, and in-app items. 100 Amazon Coins are worth $1.00 to spend on apps, games, and in-app items. Coins you buy never expire. Use Amazon Coins on Fire tablets, Fire TV, and on any Android device through the Amazon Appstore. The purchase of Amazon Coins is not taxable; however, in select US States, applicable taxes will apply when Amazon Coins are used for purchase of digital goods.', 80,6),
	--Card--
('Pokemon Grass Collection','ULTIMATE GRASS COLLECTION - Unleashed the power of Grass. This collection contains the most powerful grass pokemon cards ever. Comes with 5 rare grass Pokémon cards and 1 grass ultra-rare pokemon card. ULTIMATE GRASS COLLECTION - Unleashed the power of Grass. This collection contains the most powerful grass pokemon cards ever. Comes with 5 rare grass Pokémon cards and 1 grass ultra-rare pokemon card.', 30,6),
('Yugioh Official Cards','Yugioh Official Cards Prismatic Art Collection Booster Box. 3 Prismatic Secret Rares. 8 Ultra Rares / 12 Super Rares. 27 Normal Parallel Rares. Konami Genuine Korean version (100% Original Items).', 10,6),
('NBA Basketball Hit Collection Gift Box & Collecting Guide','PACK OF 100 BASKETBALL CARDS: Each of our basketball card collections contain 100 high-quality cards that are a blend of New and Vintage that any NBA fan would love to have! Our massive collection of Basketball Trading Cards spans many years of NBA history and contains some of the best players to play the game.',30,6),
('I Know Collection Affirmation Cards','THE POWER OF MANIFESTATION -- If you truly believe in the power of manifestation, the Dreamers affirmation cards by I Know Collection are the right way to start nurturing self-confidence, positivity, and courage, leaving behind everything that keeps you from reaching your goals.', 20, 6),
('Hallmark All Occasion Handmade Boxed Set of Assorted Greeting Cards with Card Organizer ','Fun and festive boxed set contains everything you need to celebrate throughout the year: 24 greeting cards with coordinating envelopes and a storage box with dividers to keep cards neatly organized. Fun and festive boxed set contains everything you need to celebrate throughout the year: 24 greeting cards with coordinating envelopes and a storage box with dividers to keep cards neatly organized.', 25,6),
--SPORTS--
	--Adidas--
('Adidas Free Lift 3 Bar T Shirt Mens','This adidas Free Lift 3 Bar T Shirt is crafted with short sleeves and a crew neck for a classic look. It features flat lock seams to prevent chafing and is a lightweight construction. This t shirt is designed with a signature logo and is complete with adidas branding.', 20,7),
('Arsenal Home Shirt 2020 2021','Cheer on The Gunners in style with this Arsenal Home Shirt for the 20/21 season which pays homage to the clubs former Highbury home thanks to the all-over print which is inspired by the tiles that graced the interior of the iconic stadium. The jersey benefits from being engineered with Aeroready technology which sweeps moisture away from the skin and dries quickly to maximise comfort, while the adidas branding and team crest completes the on-pitch look',50,7),
('Mens Sereno Training Shorts',
'The stunning adidas Sereno 14 Shorts Mens are made with ClimaLite mesh fabric that will wick sweat from the skin, helping you to keep dry and comfortable during your matches or training sessions. These Men is Football Shorts are finished with ultimate style, featuring the adidas 3 stripes to the legs, have an ergonomic seam design and the adidas logo showcases on the left thigh. You definitely do not want to miss out on these ones.',10,7),
('Pureboost Mens Trainers','A training plan is only as good as the effort you put into its execution. These adidas running shoes support your dedication with the incredible energy return of Boost. The upper is made with recycled materials, so your run will feel great in more ways than one.',70,7),
('Adidas Supernova Running Shoes Mens size 6','Achieve your running goals while wearing these Supernova Running Shoes from adidas. Constructed with a breathable mesh upper, these lightweight lace-up trainers are crafted with flexible cushioning to the forefoot and responsive boost cushioning to the heel for a comfortable step while the rubber outsole ensures excellent traction on all surfaces. Created with targeted support for enhanced energy return, the design is complete with adidas branding.',40,7),
('ADIDAS Galaxy 5 Runners Mens','Go the distance with these men Galaxy 5 runners from Adidas. These creps are made with a lightweight mesh upper for breathable support. With a lace closure for a locked in fit, they feature a OrthoLite sockliner and textile lining for a fresh fit. Sat on a cushioned Cloud-foam mid-sole for a smooth ride and rubber out-sole for traction, these trainers are finished up with the iconic 3-Stripes to the sidewalls.',30,7),
('Grand Court Mens Trainers','A timeless classic - these adidas Grand Court Men Trainers are perfect for any occasion. They feature a cloudfoam midsole, as well as a padded ankle collar for supreme comfort. The classic off-duty look is completed with a leather upper, and iconic adidas three stripe branding.', 30,7),
	--Nike--
('Phantom GT Elite DF FG Football Boots','These Phantom GT Elite Football Boots have been developed with a Dynamic Fit collar which delivers a snug, comfortable and supportive fit around the ankle. The boots benefit from having texturing across the upper which is thicker and denser at the instep and toe for superior control and accuracy, while the Flyknit construction provides a close-to-the-ball feel with the support to weave around players with ease.',200,7),
('Air Max 270 Mens Trainers','These Air Max 270 trainers from Nike have been engineered with a soft foam midsole with an oversized air unit in the heel for exceptional comfort with every step, while the stretchy inner sleeve and booty-like construction provides a personalised fit. The trainers have rubber on the outsole to boost traction and durability, while the pull tab on the heel provides an easy on and off and the Nike Swoosh branding completes the design.',100,7),
('Air Max Invigor Trainers Mens','Inspired by the iconic Air Max 95, the Invigor trainers have been engineered with a breathe tech upper which is light, airy and full of texture. The shoes have a no-sew skins which deliver a sleek and sporty look, whereas the foam midsole is assisted by the visible air unit in the heel to delivers incredible all-day comfort with every step. The rubber outsole offers durable traction, while the lace fastening provides a locked in feel ad the Nike Swoosh branding adds the finishing touch.',50,7),
('Utility Beanie','The crown of the Nike Sportswear beanie is made from a durable, warm knit material that offers additional benefits in cool temperatures. In contrast to the crown material, the ribbed cuff features an embroidered, durable graphic.', 15,7),
('Jumpman Men s Short-Sleeve Crew T Shirt','The Air Jordan Jumpman Mens Short-Sleeve Crew T Shirt is a great addition to any casual wardrobe, featuring a lightweight construction with a crew neck collar, short sleeves and flat lock seams that provides a comfortable fit, the classic Jumpman logo to the centre chest completes the look.',15,7),
('NSW Rpt Hood Sn21','Pre-Order this item today and receive your order shortly after the date shown. Please note your entire order will be held until all items are available.',50,7),
('Air Max Bolt Trainers Mens','Do it all while wearing the Air Max Bolt Men Trainer from Nike. This lightweight running-inspired shoe features a breathable mesh upper with lace closure with synthetic overlays for durable wear. There is a foam midsole with responsive cushioning and a large signature Nike air unit in the back and a lasting rubber outsole for plenty of grip. A padded collar secures the foot with a tongue pull on the top, wavy design and Nike branding to finish the look.',60,7),
('Sportswear Storm-FIT Windrunner Men Hooded Jacket','Layer up this Winter with the Essential Padded Jacket from Jordan. Designed in a fresh Black colourway, this regular-fit jacket has been crafted with comfortable, durable nylon with a water-repellent outer layer for premium protection. Insulated with a lightweight synthetic fill to optimise warmth, the coat features long sleeves with elastic cuffs, and a full-length zipper that goes right up to the chin, with a storm panel and snap buttons to secure the fastening.',100,7),
	--Accessories--
('Jordan Jumpman Classic99 Metal Cap','Keep your head in the game with this Jumpman Classic 99 Metal Cap from Jordan. This cap is made from soft cotton which keeps your head covered and feeling comfy. Coming in a classic six-panel design, this cap has breathable eyelets and an adjustable strap to the back. Finished with a curved peak and signature Jumpman metallic branding to the front.',20,7),
('Swoosh Headband','Keep your concentration optimal in a match by wearing the Nike Headband, it absorbs moisture and keeps your head cool and dry allowing you to keep focussed on the game!',10,7),
('JS1 Pro Jockey Riding Hat','The JS1 pro from Charles Owen represents one of the best value Jockey Skull helmets on the market at the moment. The JS1 Pro is a deep fitting skull that has a shape which is suits the majority of heads, coming in standard and also a round fit. The outer shell on Charles Owen’s JS1 Pro is made from an impact-resistant ABS plastic outer meaning the hat is one of the lightest in Charles Owens range',60,7),
('Miler Running Gloves Mens','Dont let bad weather knock you off your stride with these Mens Nike Miler Running Gloves. They are crafted with Dri-FIT technology which wicks sweat away from the body, leaving the wearer dry, warm and comfortable. The stretch fit hugs your hand and the classic look is completed with a reflective Nike Swoosh on the back of the gloves.', 10,7),
('Aquaspine Goalkeeper Gloves','The Sondico Aquaspine Mens Goalkeeper Gloves feature a high performance foam palm to give exceptional grip and comfort! The integrated finger protect system helps to prevent finger overextension backwards by including reinforced flexible bars over the top of the fingers. Complete with a flex hook and loop tape wrist strap for quick and firm closure.',20,7),
('Barcelona Prestige Ball','FC Barcelona Prestige BallThe FC Barcelona Prestige Football features tight seam tolerance for a consistent feel, while the multi-panel design provides accurate ball flight. It features FC Barcelona graphics honouring the legendary football club.',10,7),
('X365 Golf Gloves Ladies','The Mens Nike Match-FA19 Goal Keeper Gloves are perfect for training sessions and matches, crafted with a smooth latex palm that allows for better handling with the ball, a wide elasticated wrist strap and a touch tape fastening for a secure fit, completed with the Nike Swoosh branding.',10,7),
('Ikon Stand Bag Junior','The Slazenger Micro Stand Bag is a great and stable option when hitting the green- it benefits from a foldaway 2 point stand as well as a highly padded shoulder strap which is full adjustable for a more customised fit. A carry handle is also featured to assist with transportation. This stand bag is complete with 4 zipped fastened pockets and 4 dividers for your clubs. Slazenger branding completes the look.',40,7),

--TOYS&GAMES--
	--Dolls & Accessories--
('Madame Alexander 12" Mint Check Huggums Baby Doll','Mint Check: This classic 12” baby doll is perfect for tiny hands. Features blue sleep eyes, light brown painted hair and cloth hands and feet. Soft body is meant to be hugged. Recommended for ages 2 plus. Mint Check: This classic 12” baby doll is perfect for tiny hands. Features blue sleep eyes, light brown painted hair and cloth hands and feet. Soft body is meant to be hugged. Recommended for ages 2 plus',40,8),
('You & Me Get Well Baby Doll','Package Dimensions: 36.093 H x 10.312 L x 16.205 W (centimeters). Set comes with stethoscope, and 5 medicine accessories to make your baby feel better. Package Weight: 0.522 kilograms. Country of Origin : China',15,8),
('LOL Surprise OMG Remix Pop B.B. Fashion Doll',' Hair Brush, Doll Stand, Magazine, and Record Player Package - for Girls Ages 4+. UNBOX 25 SURPRISES with LOL Surprise OMG Remix fashion doll, Pop B.B. She has stunning features, styled hair and articulated for tons of posesFASHION REMIX: Pop B.B. comes with 2 fashion looks, but her 2nd outfit got remixed with her BFF, Kitty K. Collect both to complete her look.',17,8),
('Barbie Signature 2021 Holiday Doll','2021 Holiday Barbie doll reflects the magic of the season in a gorgeous gown, sparkling with sophisticated glamour. Her elegant floor-length dress features off-the-shoulder ruched sleeves and a metallic bodice with dazzling sculpted “gemstones”. Accented with a tulle peplum and silvery accents, her full skirt sparkles from every angle',30,8),
('Barbie Club Chelsea Doll and School Playset, 6-inch Blonde, with Accessories, Gift for 3 to 7 Year Olds','Barbie Club Chelsea dolls and toys inspire imaginations to explore the world with fun themes kids love – like this Chelsea school playset with multiple play areas and pieces that can be arranged and rearranged for storytelling fun! A classroom area inspires storytelling with desk and chair sets for Chelsea and a friend (sold separately) and a flipping blackboard with fun graphics.',20,8),
('Barbie Dreamhouse','Measuring 43 inches tall and 41 inches wide, the fully furnished Barbie DreamHouse inspires endless imagination with 10 indoor and outdoor play areas, customizable features and 75+ storytelling pieces! Dreamy features include a working elevator, party room with a DJ booth, second-story slide with a pool, balcony with a repositionable hammock swing and a puppy play area with its own pool and slide.',100,8),
('Gabbys Dollhouse, Magical Musical Cat Ears with Lights, Music, Sounds and Phrases, Kids Toys for Ages 3 and up','GABBY’S CAT EARS: The Magical Musical Ears bring Gabby’s signature cat ears from the show to life! With sparkly details, slide them on and feel just like Gabby as you create your own exciting adventures! LIGHTS AND OVER 10 SOUNDS: This interactive kids toy has over 10 sounds, phrases and songs from the show to discover! The Magical Musical Ears light up for a fun and memorable role-play experience.',20,8),
	--Puzzles--
('Yes4All Interlocking Floor Mats with Border – Foam Floor Mats/Gym Floor Mats with EVA Interlocking Tiles','COVER 12 SQ. FT: Include 12 tiles. Each tile measures 12”L x 12”W x 7/16”thick – thick from the highest point of the texture. DURABLE & NON SLIP: The non-skid textured & shock-absorbing surface provides a soft feeling when exercising on, best for comfortable workout area – a combination of high-density EVA',15,8),
('Coogam Wooden Blocks Puzzle','Wooden Blocks Puzzle are made of natural and healthy basswood with high quality and smooth surface. Non-toxic paint ensure safe play. It contained 40 pcs with a reasonable sized board ( Length: 10.6" Width: 7 " Height: 0.39"). Wooden Toys Tangram Brain Teaser Puzzle Game have several examples for shapes and things to make with it, each time you mixed up the pieces the puzzle would come out differently.', 10,8),
('Melissa & Doug See & Spell Wooden Educational Toy With 8 Double-Sided Spelling Boards and 63 Letters','SEE-AND-SPELL DEVELOPMENTAL TOY: The Melissa & Doug See & Spell learning toy is a 50 plus piece colorful wooden puzzle with easy-to-handle letters that fit into 8 2-sided cutout boards to spell 3 and 4-letter words. STURDY WOODEN CASE: For easy storage and portability, this learning toy comes with a sturdy wooden case, which is compact and easy to carry.',15,8),
('Melissa & Doug Solar System Floor Puzzle','Beautiful solar system puzzle: The Melissa & doug solar system floor puzzle includes 48 extra thick cardboard pieces that are easy for children to put together; the finished puzzle displays beautiful original artwork. Easy to clean: This solar system puzzle features an easy to clean surface that keeps your puzzle looking new, making cleanup simple after accidental spills.',10,8),
('Petstages Interactive Cat Puzzles, Slow Feeders, and Treat Dispensing Toys','GREAT FOR CURIOUS CATS : Stimulates cat natural foraging instincts. REPLACE YOUR BOWL: Treat puzzles can be used for daily feeding to encourage a healthy eating pace. KEEPS CATS BUSY: 16 hidden treat compartments keep cats occupied.FOOD SAFE MATERIALS: BPA, PVC & phthalate free. NO REMOVABLE PARTS: for safer play and easy cleaning; never worry about losing play pieces!',15,8),
('Rainforest 300 Piece Shaped Scene Puzzle','300-PIECE PUZZLE: The 300-piece Rainforest shaped scene jigsaw puzzle is perfect for kids ages 7 and up. The finished puzzle measures 23” x 16” and is fun and challenging for the entire family to complete together. COLORFUL SCENE: Brightly colored illustrations of a variety of jungle animals set the tropical scene of the puzzle. Featuring creatures and plants large and small, there is something new to find with each look.',15,8),
	--Arts & Crafts--
('Art 101 Doodle and Color 142 Pc Art Set in a Wood Carrying Case','Art 101 is a leading supplier of innovative and fun artistic products with 13 years of experience providing high-quality artistic tools at an affordable price. One of Amazon best sellers with over 10,000 5 star reviews. Includes 24 Premium Core Colored Pencils which color, shade, and blend beautifully. Includes a variety of coloring and painting mediums, including crayons, oil pastels, and watercolors',20,8),
('Crayola Ultra Clean Washable Markers','CRAYOLA BROAD LINE MARKERS: Features 40 Crayola Ultra Clean Washable Markers in assorted colors. ULTRA CLEAN WASHABLE MARKERS: Wash from skin, most washable clothing, and most painted walls. AT HOME CRAFTS & INDOOR ACTIVITIES: Keep spirits high with creative art supplies! Simple and fun crafts for kids are a great way to stay thoughtfully engaged and entertained.',10,8),
('Bravokids Toys for 3-6 Years Old Girls Boys, LCD Writing Tablet 10 Inch Doodle Board, Electronic Drawing Tablet Drawing Pads, Educational','EYE PROTECTION COLOR SCREEN: The LCD writing tablet adopts 2019 LCD pressure-sensitive technology and has 10-inch LCD colorful screen, easy for viewing and graffiti, free child’s imagination. This drawing tablet without radiation, no glare, safe and comfortable, even kids use for a long time. Educational birthday girl gifts.',20,8),
('Creativity for Kids Glow In The Dark Rock Painting Kit','ROCK PAINTING KIT FOR KIDS - Create unique glow in the dark painted rocks with this entertaining arts and craft set for boys and girls! Customize your painted rocks with easy to use fluorescent and glow in the dark paints. COMPLETE ARTS AND CRAFT ACTIVITY - 10 rocks are included in this Rock painting kit! This intro to rock painting kit is great for beginners and kids. Comes with everything you need to paint, decorate and hide 10 rocks.',10,8),
('Rock Painting Kit for Kids','Unleash & Spark Your Creativity: With the deluxe rock painting kit. The most Extensive set available, with standard and metallic paints, art transfers, googly eyes, gems and much more! Premium Value: Kit includes: 10 white smooth river rocks, 6 color paints, 6 metallic paints, 2 glitter glues (gold and silver), 39 transfer stickers (gold and black), googly eyes, sticky gems, 2 paintbrushes, 1 sponge, instruction guide.',15,8),
	--Building Toys--
('The Original Magnetic Building Blocks for Creative Open-Ended Play','This perfect for traveling magnetic building set features 19 Magna-Qubix pieces in traditional rainbow colors – red, orange, yellow, green, and blue. Included in this Magna-Qubix Set are the standard 3D shapes (8 one inch cubes (4 blue + 4 red), 3 orange square pyramids, 5 triangular prisms (2 yellow + 3 green) , 1 orange hexagonal prism, and 2 green rectangular prisms).',15,8),
('LEGO City Advent Calendar 60303 Building Kit','Kids aged 5 and up can enjoy imaginative play each December day with this LEGO City Advent Calendar (60303) – bursting with awesome mini-builds, fun LEGO City TV characters and cool accessories. Includes LEGO City Adventures TV series minifigure characters Top Hat Tom, Bob, Betty, Sam Grizzled, Shirley Keeper and Fendrich, plus a buildable Duke DeTain snowman and a snowy city play mat',30,8),
('LEGO City 2020 Advent Calendar 60268 Playset','The LEGO City Advent Calendar (60268) is a great introduction to the exciting world of LEGO City and the LEGO City Adventures TV series; Kids aged 5 and up can enjoy fun imaginative play throughout the holiday season. Comes with 24 gifts, including Christmas tree and Santa sleigh miniature builds, 6 LEGO City Adventures TV series minifigures, including Chief Wheeler with Santa costume, plus a city play mat with snow-cleared roads',40,8),
('PLUS PLUS BIG - Open Play Set - 100 Piece - Basic Color Mix, Construction Building Stem Toy, Interlocking Large Puzzle Blocks for Toddlers and Preschool','SIMPLE DESIGN - FUELS CREATIVITY: One shape, endless possibilities! Every brick easily connects to the next. Create colorful flat mosaics or work in 3-D to make more intricate builds. Mix and match any Plus-Plus set to bring more ideas to life!',30,8),
('Magna-Tiles ICE Set','This magnetic building set features 16 colorless Magna-Tiles pieces.. Included in this expansion Magna-Tiles Set are the standard shapes (small squares, equilateral triangles, isosceles triangles, and right triangles).. ICE Magna-Tiles are perfect pieces used to create windows, ice rinks, frozen ponds, and much more. You can even use them as “specimen cases” on your next nature walk! Collect small flowers and leaves and display them between two tiles.',25,8),

--BEAUTY&COMESTIC--
	--Make up--
('REVLON Oil-Absorbing Volcanic Face Roller','LIKE BLOTTING PAPERS, BUT BETTER: This face roller is made of real volcanic stone, which soaks up excess oil instantly. It’s our secret for fresh, shine-free skin any time. Use it on a clean or finished face—it won’t mess up your makeup. MASSAGES AND MATTIFIES FACE: Rolling the stone roller across your skin feels heavenly, like a mini facial massage. Ditch your jade roller and use our 2-in-1 Mattifying face roller for oily and acne prone skin',10,9),
('NYX PROFESSIONAL MAKEUP Mechanical Eyeliner Pencil, Black','RETRACTABLE EYE LINER: A line and defined eye is just a twist away with this eyeliner pen. Intense pigment covers like a liquid eyeliner while its creamy formula holds for hours. No need to sharpen just twist-up and apply for a winged-out eyeliner look.',5,9),
('NYX PROFESSIONAL MAKEUP Epic Ink Liner, Waterproof Liquid Eyeliner, Black','WATERPROOF LIQUID EYELINER: Get the perfect long-lasting cat eye look with NYX Professional makeup Epic Ink eyeliner.. PRECISE TIP: Our ultra-precise tip is flexible and easy to use. Every stroke is unbelievably fluid for a defined finish. Control the thickness of your lines by pressing down just a touch. Fine and natural, broad and bold the look is always up to you.',8,9),
('Glo Skin Beauty HD Mineral Foundation Stick','Lightweight, longwearing cream foundation evens & perfects for an undetectable natural skin-finish. Boosts hydration with Hyaluronic Acid, conditions with plant-based waxes & shields with natural mineral al protection',30,9),
('Glo Skin Beauty Base, Mineral Pressed Powder Foundation','PRESSED BASE: Flexible, weightless, longwearing coverage, this award-winning pressed powder base is powered by skin-protecting antioxidants and triple-milled minerals for a radiant, natural, second-skin finish.. PROTECT: Infused with antioxidants including green tea, and vitamins C and E, this anti-inflammatory, talc-free formulation provides environmental protection against aging free radical damage.',40,9),
('Glo Skin Beauty Loose Base','Great for combination and dry skin types. This loose mineral foundation formulation is beautifully pigmented and luminescent. It offers sheer to full coverage with a dewy finish. Talc free and noncomedogenic, this formula provides broad spectrum environmental protection for radiant and healthy skin. Includes our exclusive antioxidant blend of Vitamins A, C, E and Green Tea Extract. PRO TIP: Layer on top of a liquid or cream foundation for additional coverage.',30,9),
('Foundation with Concealer & Finishing Powder - Medium to Full Coverage Foundation Makeup - Cruelty-Free & Vegan Friendly','4-in-1 Pressed Mineral Makeup Broad Spectrum SPF 15 is a universal, all-in-one concealer, powder and SPF 15 and skincare for daily medium to full coverage.',20,9),
	--Skin Care--
('CeraVe Moisturizing Cream Body and Face','[ HYALURONIC ACID MOISTURIZER ] With hyaluronic acid, ceramides and MVE technology for 24 hour hydration. Rich, velvety texture that leaves skin feeling smooth, it is absorbed quickly for softened skin without greasy, sticky, feel.',15,9),
('CeraVe Hydrating Facial Cleanser ','[ DAILY FACE WASH ] Gentle cleansing lotion with hyaluronic acid, ceramides, and glycerin to help hydrate skin without stripping moisture. Removes face makeup, dirt, and excess oil, provides 24-hour hydration and leaves a moisturized, non-greasy feel.',14,9),
('EltaMD UV Clear Facial Sunscreen Broad-Spectrum SPF 46 Face Sunscreen','Oil-free EltaMD UV Clear facial sunscreen is recommended by dermatologists as it helps calm and protect sensitive skin types prone to acne, rosacea and discoloration. This zinc oxide facial sunscreen with broad- spectrum coverage protects against UVA and UVB rays from the sun.',30,9),
('Aveeno Daily Moisturizing Body Lotion','18-fluid ounce pump bottle of Aveeno Daily Moisturizing Body Lotion to moisturize dry skin for a full 24 hours. Nourishing lotion contains a unique soothing oatmeal formula that absorbs quickly, leaving your skin soft, beautiful and healthy-looking. Clinically proven and award winning fragrance-free daily lotion for dry skin locks in moisture and improves skin health in just 1 day',8,9),
('Gold Bond Ultimate Rough & Bumpy Daily Skin Therapy','Helps to improve hydration, miniaturization and dryness.. Daily therapy cream. Fragrance free, Non greasy, Non Irritating. Helps Exfoliate and Moisturize to Smooth, Soften, and Reduce The Appearance and Feel of Bumps and Rough Skin Patches',10,9),
('Dove Body Wash Hypoallergenic','Gently cleanses: Dove Sensitive Skin Body Wash combines moisture renew blend with our gentlest ingredients to pamper sensitive skin, Unlike ordinary body soap or shower gel. Mild and pH-balanced: Dove Body Wash includes moisture renew blend-a combination of skin-natural nourishes and plant-based moisturizers that absorb deeply into the top layers of skin.',25,9),
	--Hair Care--
('Alba Botanica Ocean Surf Shampoo','One 12 oz. bottle of Alba Botanica Ocean Surf Shampoo. For dry, troubled hair. Enriched with marine botanicals and tropical extracts, this formula is show in testing to repair split ends and decrease breakage. No parabens, phthalates or synthetic fragrances. 100% vegetarian formula', 10,9),
('REVLON One-Step Hair Dryer And Volumizer Hot Air Brush, Black','Style, Dry & Volumize Your Hair in One Step, Max Drying Power with 30% Less Frizz and helps reduce hair damage. Unique Non-Detachable Oval Brush Design for Smoothing the Hair, while the round edges create volume. Designed with Nylon Pin & Tufted Bristles for detangling, improved volume, and control',30,9),
('REVLON 1875W Volume Booster Hair Dryer','Wattage of this appliance may vary depending on the location of use.. 1875 Watt drying power for voluminous lift and body. 3 Heat / 2 speed settings for complete styling flexibility. Cool shot button to set your style. Removable end cap, protective anti-slip bumpers. Smoothing concentrator for precise drying and styling and volumizing diffuser softens airflow to define natural curls and waves',15,9),
('Olaplex Hair Perfector No 3 Repairing Treatment','OLAPLEX No.3 Hair Perfector - Repairing Treatment, 3.3oz. Repair damaged hair and broken bonds with olaplex. Suggest to use: Dampen hair and apply from roots to ends. Use once a week or two to three times a week for damaged hair.',25,9),
('Moroccanoil Treatment Oil','A multitasking hair treatment infused with argan oil to promote a healthier look and feel. Use as a styling routine foundation or to refresh second-day strands. Conditions, smooths frizz and flyaways, detangles, and boosts shine by up to 118%.*',40,9),
('PURA D OR Biotin Original Gold Label Anti-Thinning (16oz x 2) Shampoo & Conditioner Set','PURA D OR IS THE LEADER IN HAIR THINNING THERAPY FOR THICKER & FULLER HAIR: PURA D OR Original Gold Label Anti Hair-Thinning Shampoo and Biotin Conditioner Combo is proven & tested to reduce hair thinning. It promotes hair strength & thickness with increased volume & reducing breakage. Results may vary',40,9),
	--Foot, Hands, Nails Care--
('Flexitol Heel Magic For Dry Skin or Rough Heels', 'Foot Treatment Balm: This super concentrated moisturizer and exfoliator is clinically proven to soften and repair rough, dry, and cracked feet, replenishing moisture deep below the surface of the skin.', 10,9),
('Softsoap Liquid Hand Soap, Fresh Breeze','Light, fresh scented liquid hand soap. Wash hands often for good hand hygiene.Paraben free and formulated without phthalates. Rich lathering soap that leaves hands feeling soft. Dermatologist tested, gentle on hands. Pack of six, 7.5 fluid Ounce (Total of 45 fluid ounce)',5,9),
('AHAVA Dermud Intensive Hand Cream','Rich, intensive Dead Sea mud hand cream that repairs and hydrates even the most damaged hands to provide instant relief. Rich, intensive Dead Sea mud hand cream that repairs and hydrates even the most damaged hands to provide instant relief. Rich, intensive Dead Sea mud hand cream that repairs and hydrates even the most damaged hands to provide instant relief.',30,9),
('Foot Peel Mask 3 Pack','Exfoliator Peel Off Calluses Dead Skin Callus Remover，Baby Soft Smooth Touch Feet-Men Women . KYRTCB WEARABLE SOCK TYPE FOOT MASK:Our foot mask designed to wrap your feet like socks, that allows the feet to absorb the essence in all directions. you can wear regular socks over the foot masks to keep the mask close to the skin, and to aid with walking.',15,9),
('UV LED Nail Lamp, SUNUV Gel Nail Light for Nail Polish 48W UV Dryer with 3 Timers SUNone','UV LED Nail Lamp, SUNUV Gel Nail Light for Nail Polish 48W UV Dryer with 3 Timers SUNone. Quick Drying and Wide Compatibility: Your average curing time is shortened by 50% with SUNUV. Fast curing with all your favorite nail gel brands from beginner to professional grades. Exact curing time of your nail polishes, bases, top coating and gels can be found on its product packing or user manuals.',20,9),
('Beurer 24-piece Professional Manicure & Pedicure Nail Drill Kit','10 STAINLESS STEEL ATTACHMENTS: The kit includes 10 stainless steel attachments that are made from durable sapphire and felt as opposed to plastic and 10 sanding bands. Replacement pieces are available for purchase on Amazon. 18 SPEED SETTINGS: With enough adjustable speed to customize your mani or pedi, get the spa experience right from your home.',30,9)

INSERT INTO Bidders VALUES
('Admin', 1234567, 01234567),

